import { useState, useRef, useCallback, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { liftApi } from '../../api/services';
import type { CadEngine } from '../core/CadEngine';
import type { DrawingType, LiftParams } from '../core/types';
import { DrawingSerializer } from '../persistence/DrawingSerializer';
import { DrawingApiClient } from '../persistence/DrawingApiClient';
import { DxfExporter } from '../export/DxfExporter';
import { SvgExporter } from '../export/SvgExporter';
import { PdfExporter } from '../export/PdfExporter';
import CadCanvas, { type CadCanvasHandle } from './CadCanvas';
import CadToolbar from './CadToolbar';
import LayerPanel from './LayerPanel';
import PropertyPanel from './PropertyPanel';
import CommandInput from './CommandInput';
import StatusBar from './StatusBar';
import ThreeDViewer from './ThreeDViewer';

const DRAWING_TYPES: { key: DrawingType; label: string }[] = [
  { key: 'cross-section', label: 'Kuyu Kesiti' },
  { key: 'longitudinal', label: 'Boyuna Kesit' },
  { key: 'machine-room', label: 'Makine Dairesi' },
  { key: 'cabin-plan', label: 'Kabin Planı' },
  { key: 'pit-detail', label: 'Kuyu Dibi' },
  { key: 'overhead-detail', label: 'Kuyu Kafası' },
];

/**
 * Full page layout composing all CAD panels.
 * Drawing type tabs, load/save, auto-generate on first load.
 */
export default function CadDrawingPage() {
  const { id } = useParams<{ id: string }>();
  const canvasRef = useRef<CadCanvasHandle>(null);
  const [engine, setEngine] = useState<CadEngine | null>(null);
  const [activeType, setActiveType] = useState<DrawingType>('cross-section');
  const [view3D, setView3D] = useState(false);
  const [saving, setSaving] = useState(false);
  const [liftParams, setLiftParams] = useState<LiftParams | null>(null);

  const serializer = useRef(new DrawingSerializer());
  const apiClient = useRef(new DrawingApiClient());

  const { data: lift } = useQuery({
    queryKey: ['lift', id],
    queryFn: () => liftApi.getById(id!),
  });

  // Convert lift data to LiftParams
  useEffect(() => {
    if (!lift) return;
    const params: LiftParams = {
      id: lift.id,
      asansorTipi: lift.asansorTipi as any,
      tahrikKodu: lift.tahrikKodu as any,
      yonKodu: lift.yonKodu as any,
      kuyuGenisligi: lift.kuyuGenisligi,
      kuyuDerinligi: lift.kuyuDerinligi,
      kuyuDibi: lift.kuyuDibi,
      kuyuKafa: lift.kuyuKafa || 3500,
      kabinGenisligi: lift.kabinGenisligi || (lift.kuyuGenisligi - 400),
      kabinDerinligi: lift.kabinDerinligi || (lift.kuyuDerinligi - 400),
      kabinYuksekligi: 2200,
      kapiGenisligi: lift.kapiGenisligi,
      kapiTipi: lift.kapiTipi,
      beyanYuk: lift.beyanYuk,
      durakSayisi: lift.durakSayisi,
      floors: lift.floors || [],
      kabinRayStr: lift.kabinRayStr,
      agrRayStr: lift.agrRayStr,
      panoramik: lift.panoramik,
    };
    setLiftParams(params);
    if (engine) engine.updateLiftParams(params);
  }, [lift, engine]);

  const onEngineReady = useCallback((eng: CadEngine) => {
    setEngine(eng);
  }, []);

  // Load or auto-generate drawing when type changes
  useEffect(() => {
    if (!engine || !id || !liftParams) return;
    loadOrGenerate(engine, activeType, id, liftParams);
  }, [engine, activeType, id, liftParams]);

  const loadOrGenerate = async (eng: CadEngine, type: DrawingType, liftId: string, params: LiftParams) => {
    try {
      const json = await apiClient.current.loadDrawing(liftId, type);
      if (json) {
        serializer.current.deserialize(json, eng.entityModel, eng.viewportState);
      } else {
        // Auto-generate
        eng.entityModel.clear();
        eng.autoDrawingGenerator.clearAutoGenerated();
        eng.autoDrawingGenerator.generate(type, params);
        // Zoom to extents
        const entities = eng.entityModel.getAllEntities();
        if (entities.length > 0) {
          let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
          for (const e of entities) {
            if ((e as any).start) { minX = Math.min(minX, (e as any).start.x); minY = Math.min(minY, (e as any).start.y); maxX = Math.max(maxX, (e as any).start.x); maxY = Math.max(maxY, (e as any).start.y); }
            if ((e as any).end) { maxX = Math.max(maxX, (e as any).end.x); maxY = Math.max(maxY, (e as any).end.y); }
            if ((e as any).center) { const c = (e as any).center; const r = (e as any).radius || 0; minX = Math.min(minX, c.x - r); minY = Math.min(minY, c.y - r); maxX = Math.max(maxX, c.x + r); maxY = Math.max(maxY, c.y + r); }
            if ((e as any).vertices) { for (const v of (e as any).vertices) { minX = Math.min(minX, v.x); minY = Math.min(minY, v.y); maxX = Math.max(maxX, v.x); maxY = Math.max(maxY, v.y); } }
          }
          if (isFinite(minX)) eng.viewportState.zoomExtents({ minX, minY, maxX, maxY });
        }
      }
    } catch {
      // On error, auto-generate
      eng.entityModel.clear();
      eng.autoDrawingGenerator.generate(type, params);
    }
  };

  const handleSave = async () => {
    if (!engine || !id) return;
    setSaving(true);
    try {
      const json = serializer.current.serialize(engine.entityModel, engine.viewportState, activeType, id);
      await apiClient.current.saveDrawing(id, activeType, json);
    } catch (err) {
      console.error('Save failed:', err);
    }
    setSaving(false);
  };

  const handleExportDxf = () => {
    if (!engine) return;
    const exporter = new DxfExporter();
    const dxf = exporter.export(engine.entityModel);
    downloadFile(dxf, `${activeType}-${id}.dxf`, 'application/dxf');
  };

  const handleExportSvg = () => {
    if (!engine) return;
    const exporter = new SvgExporter();
    const svg = exporter.export(engine.entityModel);
    downloadFile(svg, `${activeType}-${id}.svg`, 'image/svg+xml');
  };

  const handleExportPdf = async () => {
    if (!engine) return;
    const exporter = new PdfExporter();
    const blob = await exporter.exportPdf(engine.entityModel, engine.viewportState);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeType}-${id}.png`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabStyle = (active: boolean): React.CSSProperties => ({
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 600,
    background: active ? 'var(--primary)' : 'transparent',
    color: active ? 'white' : 'var(--text-light)',
    border: 'none',
    borderBottom: active ? '2px solid var(--primary)' : '2px solid transparent',
    cursor: 'pointer',
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: 'calc(100vh - 56px)', overflow: 'hidden' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '4px 12px', background: '#f8fafc', borderBottom: '1px solid var(--border)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Link to={`/lifts/${id}`} style={{ fontSize: 13 }}>← Asansöre Dön</Link>
          <span style={{ color: 'var(--text-light)', fontSize: 13 }}>|</span>
          <span style={{ fontWeight: 600, fontSize: 15 }}>CAD Çizim</span>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button onClick={() => setView3D(!view3D)} style={{ padding: '4px 12px', fontSize: 12, background: view3D ? 'var(--primary)' : 'var(--border)', color: view3D ? 'white' : 'var(--text)', borderRadius: 4, border: 'none', cursor: 'pointer' }}>
            {view3D ? '2D Görünüm' : '3D Görünüm'}
          </button>
          <button onClick={handleSave} disabled={saving} style={{ padding: '4px 12px', fontSize: 12, background: 'var(--success)', color: 'white', borderRadius: 4, border: 'none', cursor: 'pointer' }}>
            {saving ? 'Kaydediliyor...' : '💾 Kaydet'}
          </button>
        </div>
      </div>

      {/* Drawing type tabs */}
      <div style={{ display: 'flex', background: '#f1f5f9', borderBottom: '1px solid var(--border)' }}>
        {DRAWING_TYPES.map((dt) => (
          <button key={dt.key} style={tabStyle(activeType === dt.key)} onClick={() => setActiveType(dt.key)}>
            {dt.label}
          </button>
        ))}
      </div>

      {view3D ? (
        <ThreeDViewer liftParams={liftParams} />
      ) : (
        <>
          {/* Toolbar */}
          <CadToolbar engine={engine} onExportDxf={handleExportDxf} onExportPdf={handleExportPdf} onExportSvg={handleExportSvg} />

          {/* Main content */}
          <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
            {/* Left panel */}
            <div style={{ width: 200, borderRight: '1px solid var(--border)', overflowY: 'auto', background: '#fafafa' }}>
              <LayerPanel engine={engine} />
            </div>

            {/* Canvas */}
            <div style={{ flex: 1, position: 'relative' }}>
              <CadCanvas ref={canvasRef} onEngineReady={onEngineReady} />
            </div>

            {/* Right panel */}
            <div style={{ width: 220, borderLeft: '1px solid var(--border)', overflowY: 'auto', background: '#fafafa' }}>
              <PropertyPanel engine={engine} />
            </div>
          </div>

          {/* Command input */}
          <CommandInput engine={engine} />

          {/* Status bar */}
          <StatusBar engine={engine} />
        </>
      )}
    </div>
  );
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
