import { useState, useRef, useCallback, useEffect } from 'react';
import type { CadEngine } from '../core/CadEngine';
import type { DrawingType, LiftParams, ToolName } from '../core/types';
import CadCanvas, { type CadCanvasHandle } from './CadCanvas';
import LayerPanel from './LayerPanel';
import PropertyPanel from './PropertyPanel';
import ParameterDialog from './ParameterDialog';
import { DxfExporter } from '../export/DxfExporter';
import { SvgExporter } from '../export/SvgExporter';

const DEFAULT_LIFT_PARAMS: LiftParams = {
  id: 'default',
  asansorTipi: 'EA',
  tahrikKodu: 'DA',
  yonKodu: 'SOL',
  kuyuGenisligi: 2000,
  kuyuDerinligi: 2500,
  kuyuDibi: 1500,
  kuyuKafa: 3600,
  kabinGenisligi: 1400,
  kabinDerinligi: 2050,
  kabinYuksekligi: 2200,
  kapiGenisligi: 900,
  kapiTipi: 'KK-OT',
  beyanYuk: 630,
  beyanKisi: 8,
  durakSayisi: 5,
  ilkDurakNo: -1,
  katYuksekligi: 3000,
  floors: [
    { katNo: -1, katRumuz: 'B1', katYuksekligi: 2800, mimariKot: '-2.80' },
    { katNo: 0, katRumuz: 'Z', katYuksekligi: 0, mimariKot: '0.00' },
    { katNo: 1, katRumuz: '1', katYuksekligi: 3000, mimariKot: '3.00' },
    { katNo: 2, katRumuz: '2', katYuksekligi: 3000, mimariKot: '6.00' },
    { katNo: 3, katRumuz: '3', katYuksekligi: 3000, mimariKot: '9.00' },
  ],
  kabinRayStr: '70x65x9',
  agrRayStr: '50x50x5',
  panoramik: false,
  // Extended ASNCAD params
  kabinYEksen: 100,
  kabinRayUcu: 15,
  kabinRayFark: 100,
  kizakKalin: 16,
  krx: 70, kry: 65, krz: 9,
  arx: 50, ary: 50, arz: 5,
  agrGen: 200,
  agrDuv: 50,
  agrU: 50,
  agrUz: 80,
  agrGir: 0,
  agrKabin: 0,
  tahrikKas: 400,
  sapKas: 200,
  mdTahrikKas: 320,
  mdSapKas: 200,
  regYer: 'SOL',
  kabinTamponu: 'YTampon1#YTamponBK#YTamponKK',
  agrTamponu: 'YTampon1#YTamponBK#YTamponKK',
  dengeZinciri: false,
  iskeleVar: false,
  mentese: 'SOL',
  kapiH: 2100,
  esikKalin: 10,
  duvarKal: 200,
  seyirMesafesi: 12000,
  mdTabTavan: 2100,
  hamdGen: 0,
  hamdDer: 0,
  makYon: 'SOL',
  firmaAd: '', firmaAdres: '', firmaTel: '', firmaFax: '', firmaMail: '',
  firmaYetkili: '', firmaMarka: '',
  mmAd: '', mmOda: '', mmBel: '', mmSmm: '',
  emAd: '', emOda: '', emBel: '', emSmm: '',
};

const DRAWING_TYPES: { key: DrawingType; label: string }[] = [
  { key: 'cross-section', label: 'Kuyu Kesiti' },
  { key: 'longitudinal', label: 'Boyuna Kesit' },
  { key: 'machine-room', label: 'Makine Dairesi' },
  { key: 'cabin-plan', label: 'Kabin Planı' },
  { key: 'pit-detail', label: 'Kuyu Dibi' },
  { key: 'overhead-detail', label: 'Kuyu Kafası' },
];

const DRAW_TOOLS: { name: ToolName; icon: string; label: string }[] = [
  { name: 'select', icon: '⬚', label: 'Seç' },
  { name: 'line', icon: '╱', label: 'Çizgi' },
  { name: 'polyline', icon: '⏤', label: 'Polyline' },
  { name: 'rectangle', icon: '▭', label: 'Dikdörtgen' },
  { name: 'circle', icon: '○', label: 'Daire' },
  { name: 'arc', icon: '◠', label: 'Yay' },
  { name: 'dimension', icon: '↔', label: 'Ölçü' },
  { name: 'text', icon: 'A', label: 'Yazı' },
];

const MANIP_TOOLS: { name: ToolName; icon: string; label: string }[] = [
  { name: 'move', icon: '✥', label: 'Taşı' },
  { name: 'copy', icon: '⧉', label: 'Kopyala' },
  { name: 'rotate', icon: '↻', label: 'Döndür' },
  { name: 'scale', icon: '⤢', label: 'Ölçekle' },
  { name: 'mirror', icon: '⇿', label: 'Ayna' },
  { name: 'offset', icon: '⟺', label: 'Ofset' },
];

export default function StandaloneCadApp() {
  const canvasRef = useRef<CadCanvasHandle>(null);
  const [engine, setEngine] = useState<CadEngine | null>(null);
  const [activeType, setActiveType] = useState<DrawingType>('cross-section');
  const [activeTool, setActiveTool] = useState<ToolName>('select');
  const [showLayers, setShowLayers] = useState(true);
  const [showProps, setShowProps] = useState(true);
  const [showParamDialog, setShowParamDialog] = useState(false);
  const [cmdInput, setCmdInput] = useState('');
  const [entityCount, setEntityCount] = useState(0);
  const [ortho, setOrtho] = useState(false);
  const [snap, setSnap] = useState(true);
  const [liftParams, setLiftParams] = useState<LiftParams>(DEFAULT_LIFT_PARAMS);

  const regenerateDrawing = useCallback((eng: CadEngine, type: DrawingType, params: LiftParams) => {
    eng.entityModel.clear();
    eng.autoDrawingGenerator.clearAutoGenerated();
    eng.updateLiftParams(params);
    eng.autoDrawingGenerator.generate(type, params);
    const entities = eng.entityModel.getAllEntities();
    if (entities.length > 0) {
      eng.viewportState.zoomExtents(computeBounds(entities));
    }
    setEntityCount(eng.entityModel.getEntityCount());
  }, []);

  const onEngineReady = useCallback((eng: CadEngine) => {
    setEngine(eng);
    regenerateDrawing(eng, 'cross-section', liftParams);

    eng.on('entityAdded', () => setEntityCount(eng.entityModel.getEntityCount()));
    eng.on('entityRemoved', () => setEntityCount(eng.entityModel.getEntityCount()));
    eng.on('toolChanged', () => {
      const t = eng.toolManager.getActiveTool();
      if (t) setActiveTool(t.name);
    });
  }, [liftParams, regenerateDrawing]);

  const switchDrawingType = (type: DrawingType) => {
    if (!engine) return;
    setActiveType(type);
    regenerateDrawing(engine, type, liftParams);
  };

  const handleParamApply = (newParams: LiftParams) => {
    setLiftParams(newParams);
    setShowParamDialog(false);
    if (engine) {
      regenerateDrawing(engine, activeType, newParams);
    }
  };

  const selectTool = (name: ToolName) => {
    if (!engine) return;
    engine.activateTool(name);
    setActiveTool(name);
  };

  const handleCmd = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key !== 'Enter' || !engine || !cmdInput.trim()) return;
    const cmd = cmdInput.trim().toLowerCase();
    setCmdInput('');

    const num = parseFloat(cmd);
    if (!isNaN(num)) { engine.handleNumericInput(num); return; }

    const map: Record<string, ToolName> = {
      l: 'line', line: 'line', pl: 'polyline', polyline: 'polyline',
      rec: 'rectangle', rectangle: 'rectangle', c: 'circle', circle: 'circle',
      a: 'arc', arc: 'arc', dim: 'dimension', dimension: 'dimension',
      t: 'text', text: 'text', m: 'move', move: 'move', co: 'copy', copy: 'copy',
      ro: 'rotate', rotate: 'rotate', sc: 'scale', scale: 'scale',
      mi: 'mirror', mirror: 'mirror', o: 'offset', offset: 'offset',
      s: 'select', select: 'select',
    };
    if (map[cmd]) { selectTool(map[cmd]); return; }
    if (cmd === 'u' || cmd === 'undo') engine.undo();
    if (cmd === 'redo') engine.redo();
    if (cmd === 'del') engine.deleteSelected();
    if (cmd === 'param' || cmd === 'parametreler') setShowParamDialog(true);
  };

  const exportDxf = () => {
    if (!engine) return;
    const exp = new DxfExporter();
    const dxf = exp.export(engine.entityModel);
    download(dxf, `${activeType}.dxf`, 'application/dxf');
  };

  const exportSvg = () => {
    if (!engine) return;
    const exp = new SvgExporter();
    const svg = exp.export(engine.entityModel);
    download(svg, `${activeType}.svg`, 'image/svg+xml');
  };

  const btnStyle = (active: boolean): React.CSSProperties => ({
    padding: '5px 8px', fontSize: 14, fontWeight: 600, cursor: 'pointer',
    background: active ? '#2563eb' : '#334155', color: active ? '#fff' : '#94a3b8',
    border: 'none', borderRadius: 3, minWidth: 32, lineHeight: 1,
  });

  const tabStyle = (active: boolean): React.CSSProperties => ({
    padding: '6px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer',
    background: active ? '#2563eb' : 'transparent', color: active ? '#fff' : '#94a3b8',
    border: 'none', borderBottom: active ? '2px solid #2563eb' : '2px solid transparent',
  });

  const smallBtn: React.CSSProperties = {
    padding: '4px 8px', fontSize: 11, cursor: 'pointer',
    background: '#334155', color: '#94a3b8', border: 'none', borderRadius: 3,
  };

  const paramBtn: React.CSSProperties = {
    padding: '4px 12px', fontSize: 12, cursor: 'pointer', fontWeight: 700,
    background: '#f59e0b', color: '#0f172a', border: 'none', borderRadius: 3,
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', background: '#0f172a', color: '#e2e8f0', fontFamily: 'system-ui, sans-serif' }}>
      {/* Parameter Dialog */}
      <ParameterDialog
        open={showParamDialog}
        params={liftParams}
        onApply={handleParamApply}
        onClose={() => setShowParamDialog(false)}
      />

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 12px', height: 40, background: '#1e293b', borderBottom: '1px solid #334155' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontSize: 16, fontWeight: 700 }}>🏗️ ASNCAD Web CAD</span>
          <span style={{ fontSize: 11, color: '#64748b' }}>Asansör Tasarım ve Çizim</span>
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          <button style={paramBtn} onClick={() => setShowParamDialog(true)}>⚙️ Parametreler</button>
          <button style={smallBtn} onClick={exportDxf}>📥 DXF</button>
          <button style={smallBtn} onClick={exportSvg}>📥 SVG</button>
          <button style={smallBtn} onClick={() => setShowLayers(!showLayers)}>Katmanlar</button>
          <button style={smallBtn} onClick={() => setShowProps(!showProps)}>Özellikler</button>
        </div>
      </div>

      {/* Drawing type tabs */}
      <div style={{ display: 'flex', background: '#1e293b', borderBottom: '1px solid #334155' }}>
        {DRAWING_TYPES.map(dt => (
          <button key={dt.key} style={tabStyle(activeType === dt.key)} onClick={() => switchDrawingType(dt.key)}>
            {dt.label}
          </button>
        ))}
      </div>

      {/* Toolbar */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 3, padding: '4px 8px', background: '#1e293b', borderBottom: '1px solid #334155', alignItems: 'center' }}>
        {DRAW_TOOLS.map(t => (
          <button key={t.name} style={btnStyle(activeTool === t.name)} onClick={() => selectTool(t.name)} title={t.label}>{t.icon}</button>
        ))}
        <span style={{ width: 1, height: 20, background: '#475569', margin: '0 4px' }} />
        {MANIP_TOOLS.map(t => (
          <button key={t.name} style={btnStyle(activeTool === t.name)} onClick={() => selectTool(t.name)} title={t.label}>{t.icon}</button>
        ))}
        <span style={{ width: 1, height: 20, background: '#475569', margin: '0 4px' }} />
        <button style={smallBtn} onClick={() => engine?.undo()} title="Geri Al (Ctrl+Z)">↩</button>
        <button style={smallBtn} onClick={() => engine?.redo()} title="Yinele (Ctrl+Y)">↪</button>
        <button style={smallBtn} onClick={() => engine?.deleteSelected()} title="Sil">🗑</button>
        <button style={smallBtn} onClick={() => {
          if (!engine) return;
          const ents = engine.entityModel.getAllEntities();
          if (ents.length > 0) engine.viewportState.zoomExtents(computeBounds(ents));
        }} title="Tümüne Sığdır">⊞</button>
        <span style={{ width: 1, height: 20, background: '#475569', margin: '0 4px' }} />
        <button style={btnStyle(snap)} onClick={() => { setSnap(!snap); }} title="Snap (F3)">Snap</button>
        <button style={btnStyle(ortho)} onClick={() => { const n = !ortho; setOrtho(n); engine?.snapManager.setOrthoEnabled(n); }} title="Ortho (F8)">Ortho</button>
        <span style={{ width: 1, height: 20, background: '#475569', margin: '0 4px' }} />
        <button style={paramBtn} onClick={() => setShowParamDialog(true)} title="Asansör Parametreleri">⚙️ Parametreler</button>
      </div>

      {/* Main area */}
      <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
        {/* Left panel - Layers */}
        {showLayers && (
          <div style={{ width: 180, borderRight: '1px solid #334155', overflowY: 'auto', background: '#1e293b' }}>
            <LayerPanel engine={engine} />
          </div>
        )}

        {/* Canvas */}
        <div style={{ flex: 1, position: 'relative' }}>
          <CadCanvas ref={canvasRef} onEngineReady={onEngineReady} />
        </div>

        {/* Right panel - Properties */}
        {showProps && (
          <div style={{ width: 200, borderLeft: '1px solid #334155', overflowY: 'auto', background: '#1e293b' }}>
            <PropertyPanel engine={engine} />
          </div>
        )}
      </div>

      {/* Command input + Status bar with calculated values */}
      <div style={{ display: 'flex', alignItems: 'center', height: 28, background: '#1e293b', borderTop: '1px solid #334155', padding: '0 8px', gap: 8 }}>
        <span style={{ fontSize: 11, color: '#64748b', fontWeight: 600 }}>Komut:</span>
        <input
          value={cmdInput}
          onChange={e => setCmdInput(e.target.value)}
          onKeyDown={handleCmd}
          placeholder="Komut veya değer girin (line, circle, param...)"
          style={{ flex: 1, background: '#0f172a', color: '#e2e8f0', border: '1px solid #334155', borderRadius: 3, padding: '2px 8px', fontSize: 12, fontFamily: 'monospace', outline: 'none' }}
        />
        <span style={{ fontSize: 11, color: '#64748b' }}>Araç: {activeTool}</span>
        <span style={{ fontSize: 11, color: '#475569' }}>|</span>
        <span style={{ fontSize: 11, color: '#64748b' }}>Nesneler: {entityCount}</span>
        <span style={{ fontSize: 11, color: '#475569' }}>|</span>
        <span style={{ fontSize: 10, color: '#f59e0b' }}>
          Yük:{liftParams.beyanYuk}kg Kişi:{liftParams.beyanKisi}
        </span>
        <span style={{ fontSize: 10, color: '#60a5fa' }}>
          Kabin:{liftParams.kabinGenisligi}x{liftParams.kabinDerinligi}
        </span>
        <span style={{ fontSize: 10, color: '#94a3b8' }}>
          Kuyu:{liftParams.kuyuGenisligi}x{liftParams.kuyuDerinligi}
        </span>
        <span style={{ fontSize: 10, color: '#94a3b8' }}>
          {liftParams.asansorTipi}/{liftParams.tahrikKodu}/{liftParams.yonKodu}
        </span>
      </div>
    </div>
  );
}

function computeBounds(entities: any[]) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const e of entities) {
    if (e.start) { minX = Math.min(minX, e.start.x); minY = Math.min(minY, e.start.y); maxX = Math.max(maxX, e.start.x); maxY = Math.max(maxY, e.start.y); }
    if (e.end) { minX = Math.min(minX, e.end.x); minY = Math.min(minY, e.end.y); maxX = Math.max(maxX, e.end.x); maxY = Math.max(maxY, e.end.y); }
    if (e.center) { const r = e.radius || 0; minX = Math.min(minX, e.center.x - r); minY = Math.min(minY, e.center.y - r); maxX = Math.max(maxX, e.center.x + r); maxY = Math.max(maxY, e.center.y + r); }
    if (e.vertices) { for (const v of e.vertices) { minX = Math.min(minX, v.x); minY = Math.min(minY, v.y); maxX = Math.max(maxX, v.x); maxY = Math.max(maxY, v.y); } }
    if (e.position) { minX = Math.min(minX, e.position.x); minY = Math.min(minY, e.position.y); maxX = Math.max(maxX, e.position.x + 100); maxY = Math.max(maxY, e.position.y + 20); }
    if (e.defPoint1) { minX = Math.min(minX, e.defPoint1.x, e.defPoint2.x); minY = Math.min(minY, e.defPoint1.y, e.defPoint2.y); maxX = Math.max(maxX, e.defPoint1.x, e.defPoint2.x); maxY = Math.max(maxY, e.defPoint1.y, e.defPoint2.y); }
  }
  if (!isFinite(minX)) { minX = -1000; minY = -1000; maxX = 3000; maxY = 3000; }
  return { minX, minY, maxX, maxY };
}

function download(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
