namespace ascad
{
    using DevExpress.Utils;
    using DevExpress.XtraEditors;
    using DevExpress.XtraEditors.Controls;
    using DevExpress.XtraEditors.Mask;
    using DevExpress.XtraLayout;
    using DevExpress.XtraLayout.Utils;
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;

    public class FirmaBilgileri : Form
    {
        public SimpleButton button1;
        private IContainer components = null;
        private DateEdit dateEdit1;
        private DateEdit dateEdit2;
        private TextEdit emad;
        private TextEdit embel;
        private TextEdit emoda;
        private TextEdit emsmm;
        public LabelControl label1;
        private LabelControl labelControl1;
        private LabelControl labelControl2;
        private LabelControl labelControl3;
        private LabelControl labelControl4;
        private LabelControl labelControl5;
        private LabelControl labelControl6;
        private LabelControl labelControl7;
        private LabelControl labelControl8;
        private LabelControl labelControl9;
        private LayoutControl layoutControl2;
        private LayoutControlGroup layoutControlGroup2;
        private LayoutControlItem layoutControlItem1;
        private LayoutControlItem layoutControlItem10;
        private LayoutControlItem layoutControlItem11;
        private LayoutControlItem layoutControlItem12;
        private LayoutControlItem layoutControlItem13;
        private LayoutControlItem layoutControlItem14;
        public LayoutControlItem layoutControlItem15;
        public LayoutControlItem layoutControlItem16;
        public LayoutControlItem layoutControlItem17;
        public LayoutControlItem layoutControlItem18;
        public LayoutControlItem layoutControlItem19;
        private LayoutControlItem layoutControlItem2;
        public LayoutControlItem layoutControlItem20;
        public LayoutControlItem layoutControlItem21;
        public LayoutControlItem layoutControlItem22;
        public LayoutControlItem layoutControlItem23;
        public LayoutControlItem layoutControlItem24;
        public LayoutControlItem layoutControlItem25;
        public LayoutControlItem layoutControlItem26;
        public LayoutControlItem layoutControlItem27;
        private LayoutControlItem layoutControlItem28;
        private LayoutControlItem layoutControlItem29;
        private LayoutControlItem layoutControlItem3;
        private LayoutControlItem layoutControlItem30;
        private LayoutControlItem layoutControlItem31;
        private LayoutControlItem layoutControlItem32;
        private LayoutControlItem layoutControlItem4;
        private LayoutControlItem layoutControlItem5;
        private LayoutControlItem layoutControlItem6;
        private LayoutControlItem layoutControlItem7;
        private LayoutControlItem layoutControlItem8;
        private LayoutControlItem layoutControlItem9;
        private TextEdit mmad;
        private TextEdit mmbel;
        private TextEdit mmoda;
        private TextEdit mmsmm;
        private TextEdit textBox1;
        private TextEdit textBox2;
        private TextEdit textBox3;
        private TextEdit textBox4;
        private TextEdit textBox5;
        private TextEdit textBox6;
        private TextEdit textEdit10;
        private TextEdit textEdit11;
        private TextEdit textEdit5;
        private TextEdit textEdit8;
        private TextEdit textEdit9;
        private abc1 xx = new abc1();

        public FirmaBilgileri()
        {
            this.InitializeComponent();
        }

        private void button1_Click_1(object sender, EventArgs e)
        {
            try
            {
                this.xx.oleupdate("update firmabilgi set ad='" + this.textBox1.Text + "', tel='" + this.textBox4.Text + "', fax='" + this.textBox5.Text + "', mail='" + this.textBox6.Text + "', yetkili='" + this.textBox3.Text + "', marka='" + this.textEdit5.Text + "', adres='" + this.textBox2.Text + "', onkurulusad='" + this.textEdit8.Text + "', onkurulusno='" + this.textEdit9.Text + "', santar='" + this.dateEdit1.Text + "', sanno='" + this.textEdit10.Text + "', hybtar='" + this.dateEdit2.Text + "', hybno='" + this.textEdit11.Text + "', mmad='" + this.mmad.Text + "', mmoda='" + this.mmoda.Text + "', mmbel='" + this.mmbel.Text + "', mmsmm='" + this.mmsmm.Text + "', emad='" + this.emad.Text + "', embel='" + this.embel.Text + "', emoda='" + this.emoda.Text + "', emsmm='" + this.emsmm.Text + "' where id=1", "");
                base.Close();
            }
            catch (Exception)
            {
                throw;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components > null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void FirmaBilgileri_Load(object sender, EventArgs e)
        {
            try
            {
                DataTable table = this.xx.dtta("select * from firmabilgi", "");
                this.textBox1.Text = table.Rows[0]["ad"].ToString();
                this.textBox4.Text = table.Rows[0]["tel"].ToString();
                this.textBox5.Text = table.Rows[0]["fax"].ToString();
                this.textBox6.Text = table.Rows[0]["mail"].ToString();
                this.textBox3.Text = table.Rows[0]["yetkili"].ToString();
                this.textEdit5.Text = table.Rows[0]["marka"].ToString();
                this.textBox2.Text = table.Rows[0]["adres"].ToString();
                this.textEdit8.Text = table.Rows[0]["onkurulusad"].ToString();
                this.textEdit9.Text = table.Rows[0]["onkurulusno"].ToString();
                this.dateEdit1.Text = table.Rows[0]["santar"].ToString();
                this.textEdit10.Text = table.Rows[0]["sanno"].ToString();
                this.dateEdit2.Text = table.Rows[0]["hybtar"].ToString();
                this.textEdit11.Text = table.Rows[0]["hybno"].ToString();
                this.mmad.Text = table.Rows[0]["mmad"].ToString();
                this.mmoda.Text = table.Rows[0]["mmoda"].ToString();
                this.mmbel.Text = table.Rows[0]["mmbel"].ToString();
                this.mmsmm.Text = table.Rows[0]["mmsmm"].ToString();
                this.emad.Text = table.Rows[0]["emad"].ToString();
                this.emoda.Text = table.Rows[0]["emoda"].ToString();
                this.embel.Text = table.Rows[0]["embel"].ToString();
                this.emsmm.Text = table.Rows[0]["emsmm"].ToString();
                string str = table.Rows[0]["dil"].ToString();
            }
            catch (Exception)
            {
                MessageBox.Show("İlk kez giriş yapıyosunuz bilgilerinizi doldurun...");
            }
        }

        private void InitializeComponent()
        {
            this.button1 = new SimpleButton();
            this.layoutControl2 = new LayoutControl();
            this.emsmm = new TextEdit();
            this.embel = new TextEdit();
            this.emoda = new TextEdit();
            this.emad = new TextEdit();
            this.mmsmm = new TextEdit();
            this.mmbel = new TextEdit();
            this.mmoda = new TextEdit();
            this.mmad = new TextEdit();
            this.labelControl9 = new LabelControl();
            this.labelControl8 = new LabelControl();
            this.labelControl7 = new LabelControl();
            this.labelControl6 = new LabelControl();
            this.labelControl5 = new LabelControl();
            this.labelControl4 = new LabelControl();
            this.labelControl3 = new LabelControl();
            this.labelControl2 = new LabelControl();
            this.labelControl1 = new LabelControl();
            this.textEdit11 = new TextEdit();
            this.dateEdit2 = new DateEdit();
            this.textEdit10 = new TextEdit();
            this.dateEdit1 = new DateEdit();
            this.textEdit9 = new TextEdit();
            this.textEdit8 = new TextEdit();
            this.textBox2 = new TextEdit();
            this.label1 = new LabelControl();
            this.textBox6 = new TextEdit();
            this.textEdit5 = new TextEdit();
            this.textBox3 = new TextEdit();
            this.textBox5 = new TextEdit();
            this.textBox4 = new TextEdit();
            this.textBox1 = new TextEdit();
            this.layoutControlGroup2 = new LayoutControlGroup();
            this.layoutControlItem15 = new LayoutControlItem();
            this.layoutControlItem25 = new LayoutControlItem();
            this.layoutControlItem26 = new LayoutControlItem();
            this.layoutControlItem5 = new LayoutControlItem();
            this.layoutControlItem22 = new LayoutControlItem();
            this.layoutControlItem23 = new LayoutControlItem();
            this.layoutControlItem18 = new LayoutControlItem();
            this.layoutControlItem24 = new LayoutControlItem();
            this.layoutControlItem27 = new LayoutControlItem();
            this.layoutControlItem21 = new LayoutControlItem();
            this.layoutControlItem6 = new LayoutControlItem();
            this.layoutControlItem19 = new LayoutControlItem();
            this.layoutControlItem16 = new LayoutControlItem();
            this.layoutControlItem20 = new LayoutControlItem();
            this.layoutControlItem17 = new LayoutControlItem();
            this.layoutControlItem1 = new LayoutControlItem();
            this.layoutControlItem2 = new LayoutControlItem();
            this.layoutControlItem3 = new LayoutControlItem();
            this.layoutControlItem4 = new LayoutControlItem();
            this.layoutControlItem7 = new LayoutControlItem();
            this.layoutControlItem8 = new LayoutControlItem();
            this.layoutControlItem9 = new LayoutControlItem();
            this.layoutControlItem10 = new LayoutControlItem();
            this.layoutControlItem11 = new LayoutControlItem();
            this.layoutControlItem12 = new LayoutControlItem();
            this.layoutControlItem13 = new LayoutControlItem();
            this.layoutControlItem14 = new LayoutControlItem();
            this.layoutControlItem28 = new LayoutControlItem();
            this.layoutControlItem29 = new LayoutControlItem();
            this.layoutControlItem30 = new LayoutControlItem();
            this.layoutControlItem31 = new LayoutControlItem();
            this.layoutControlItem32 = new LayoutControlItem();
            this.layoutControl2.BeginInit();
            this.layoutControl2.SuspendLayout();
            this.emsmm.Properties.BeginInit();
            this.embel.Properties.BeginInit();
            this.emoda.Properties.BeginInit();
            this.emad.Properties.BeginInit();
            this.mmsmm.Properties.BeginInit();
            this.mmbel.Properties.BeginInit();
            this.mmoda.Properties.BeginInit();
            this.mmad.Properties.BeginInit();
            this.textEdit11.Properties.BeginInit();
            this.dateEdit2.Properties.CalendarTimeProperties.BeginInit();
            this.dateEdit2.Properties.BeginInit();
            this.textEdit10.Properties.BeginInit();
            this.dateEdit1.Properties.CalendarTimeProperties.BeginInit();
            this.dateEdit1.Properties.BeginInit();
            this.textEdit9.Properties.BeginInit();
            this.textEdit8.Properties.BeginInit();
            this.textBox2.Properties.BeginInit();
            this.textBox6.Properties.BeginInit();
            this.textEdit5.Properties.BeginInit();
            this.textBox3.Properties.BeginInit();
            this.textBox5.Properties.BeginInit();
            this.textBox4.Properties.BeginInit();
            this.textBox1.Properties.BeginInit();
            this.layoutControlGroup2.BeginInit();
            this.layoutControlItem15.BeginInit();
            this.layoutControlItem25.BeginInit();
            this.layoutControlItem26.BeginInit();
            this.layoutControlItem5.BeginInit();
            this.layoutControlItem22.BeginInit();
            this.layoutControlItem23.BeginInit();
            this.layoutControlItem18.BeginInit();
            this.layoutControlItem24.BeginInit();
            this.layoutControlItem27.BeginInit();
            this.layoutControlItem21.BeginInit();
            this.layoutControlItem6.BeginInit();
            this.layoutControlItem19.BeginInit();
            this.layoutControlItem16.BeginInit();
            this.layoutControlItem20.BeginInit();
            this.layoutControlItem17.BeginInit();
            this.layoutControlItem1.BeginInit();
            this.layoutControlItem2.BeginInit();
            this.layoutControlItem3.BeginInit();
            this.layoutControlItem4.BeginInit();
            this.layoutControlItem7.BeginInit();
            this.layoutControlItem8.BeginInit();
            this.layoutControlItem9.BeginInit();
            this.layoutControlItem10.BeginInit();
            this.layoutControlItem11.BeginInit();
            this.layoutControlItem12.BeginInit();
            this.layoutControlItem13.BeginInit();
            this.layoutControlItem14.BeginInit();
            this.layoutControlItem28.BeginInit();
            this.layoutControlItem29.BeginInit();
            this.layoutControlItem30.BeginInit();
            this.layoutControlItem31.BeginInit();
            this.layoutControlItem32.BeginInit();
            base.SuspendLayout();
            this.button1.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.button1.Appearance.Options.UseFont = true;
            this.button1.Location = new Point(7, 0x185);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x289, 0x26);
            this.button1.StyleController = this.layoutControl2;
            this.button1.TabIndex = 0x11;
            this.button1.Text = "Kaydet / G\x00fcncelle";
            this.button1.Click += new EventHandler(this.button1_Click_1);
            this.layoutControl2.Controls.Add(this.emsmm);
            this.layoutControl2.Controls.Add(this.embel);
            this.layoutControl2.Controls.Add(this.emoda);
            this.layoutControl2.Controls.Add(this.emad);
            this.layoutControl2.Controls.Add(this.mmsmm);
            this.layoutControl2.Controls.Add(this.mmbel);
            this.layoutControl2.Controls.Add(this.mmoda);
            this.layoutControl2.Controls.Add(this.mmad);
            this.layoutControl2.Controls.Add(this.labelControl9);
            this.layoutControl2.Controls.Add(this.labelControl8);
            this.layoutControl2.Controls.Add(this.labelControl7);
            this.layoutControl2.Controls.Add(this.labelControl6);
            this.layoutControl2.Controls.Add(this.labelControl5);
            this.layoutControl2.Controls.Add(this.labelControl4);
            this.layoutControl2.Controls.Add(this.labelControl3);
            this.layoutControl2.Controls.Add(this.labelControl2);
            this.layoutControl2.Controls.Add(this.labelControl1);
            this.layoutControl2.Controls.Add(this.textEdit11);
            this.layoutControl2.Controls.Add(this.dateEdit2);
            this.layoutControl2.Controls.Add(this.textEdit10);
            this.layoutControl2.Controls.Add(this.button1);
            this.layoutControl2.Controls.Add(this.dateEdit1);
            this.layoutControl2.Controls.Add(this.textEdit9);
            this.layoutControl2.Controls.Add(this.textEdit8);
            this.layoutControl2.Controls.Add(this.textBox2);
            this.layoutControl2.Controls.Add(this.label1);
            this.layoutControl2.Controls.Add(this.textBox6);
            this.layoutControl2.Controls.Add(this.textEdit5);
            this.layoutControl2.Controls.Add(this.textBox3);
            this.layoutControl2.Controls.Add(this.textBox5);
            this.layoutControl2.Controls.Add(this.textBox4);
            this.layoutControl2.Controls.Add(this.textBox1);
            this.layoutControl2.Dock = DockStyle.Fill;
            this.layoutControl2.Location = new Point(0, 0);
            this.layoutControl2.Name = "layoutControl2";
            this.layoutControl2.Root = this.layoutControlGroup2;
            this.layoutControl2.Size = new Size(0x297, 0x1b2);
            this.layoutControl2.TabIndex = 0x11;
            this.layoutControl2.Text = "layoutControl2";
            this.emsmm.Location = new Point(0x213, 0x16b);
            this.emsmm.Name = "emsmm";
            this.emsmm.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.emsmm.Properties.Appearance.Options.UseFont = true;
            this.emsmm.Size = new Size(0x7d, 0x16);
            this.emsmm.StyleController = this.layoutControl2;
            this.emsmm.TabIndex = 0x22;
            this.embel.Location = new Point(0x191, 0x16b);
            this.embel.Name = "embel";
            this.embel.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.embel.Properties.Appearance.Options.UseFont = true;
            this.embel.Size = new Size(0x7e, 0x16);
            this.embel.StyleController = this.layoutControl2;
            this.embel.TabIndex = 0x21;
            this.emoda.Location = new Point(0x110, 0x16b);
            this.emoda.Name = "emoda";
            this.emoda.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.emoda.Properties.Appearance.Options.UseFont = true;
            this.emoda.Size = new Size(0x7d, 0x16);
            this.emoda.StyleController = this.layoutControl2;
            this.emoda.TabIndex = 0x20;
            this.emad.Location = new Point(0x7f, 0x16b);
            this.emad.Name = "emad";
            this.emad.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.emad.Properties.Appearance.Options.UseFont = true;
            this.emad.Size = new Size(0x8d, 0x16);
            this.emad.StyleController = this.layoutControl2;
            this.emad.TabIndex = 0x1f;
            this.mmsmm.Location = new Point(0x213, 0x151);
            this.mmsmm.Name = "mmsmm";
            this.mmsmm.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.mmsmm.Properties.Appearance.Options.UseFont = true;
            this.mmsmm.Size = new Size(0x7d, 0x16);
            this.mmsmm.StyleController = this.layoutControl2;
            this.mmsmm.TabIndex = 30;
            this.mmbel.Location = new Point(0x191, 0x151);
            this.mmbel.Name = "mmbel";
            this.mmbel.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.mmbel.Properties.Appearance.Options.UseFont = true;
            this.mmbel.Size = new Size(0x7e, 0x16);
            this.mmbel.StyleController = this.layoutControl2;
            this.mmbel.TabIndex = 0x1d;
            this.mmoda.Location = new Point(0x110, 0x151);
            this.mmoda.Name = "mmoda";
            this.mmoda.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.mmoda.Properties.Appearance.Options.UseFont = true;
            this.mmoda.Size = new Size(0x7d, 0x16);
            this.mmoda.StyleController = this.layoutControl2;
            this.mmoda.TabIndex = 0x1c;
            this.mmad.Location = new Point(0x7f, 0x151);
            this.mmad.Name = "mmad";
            this.mmad.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.mmad.Properties.Appearance.Options.UseFont = true;
            this.mmad.Size = new Size(0x8d, 0x16);
            this.mmad.StyleController = this.layoutControl2;
            this.mmad.TabIndex = 0x1b;
            this.labelControl9.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labelControl9.Location = new Point(7, 0x16b);
            this.labelControl9.Name = "labelControl9";
            this.labelControl9.Size = new Size(0x74, 0x16);
            this.labelControl9.StyleController = this.layoutControl2;
            this.labelControl9.TabIndex = 0x1a;
            this.labelControl9.Text = "ELEKTRİK M\x00dcH.";
            this.labelControl8.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labelControl8.Location = new Point(7, 0x151);
            this.labelControl8.Name = "labelControl8";
            this.labelControl8.Size = new Size(0x74, 0x16);
            this.labelControl8.StyleController = this.layoutControl2;
            this.labelControl8.TabIndex = 0x19;
            this.labelControl8.Text = "MAKİNA M\x00dcH.";
            this.labelControl7.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labelControl7.Location = new Point(0x213, 0x13e);
            this.labelControl7.Name = "labelControl7";
            this.labelControl7.Size = new Size(0x7d, 15);
            this.labelControl7.StyleController = this.layoutControl2;
            this.labelControl7.TabIndex = 0x18;
            this.labelControl7.Text = "SMM BELGE NO";
            this.labelControl6.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labelControl6.Location = new Point(0x191, 0x13e);
            this.labelControl6.Name = "labelControl6";
            this.labelControl6.Size = new Size(0x7e, 15);
            this.labelControl6.StyleController = this.layoutControl2;
            this.labelControl6.TabIndex = 0x17;
            this.labelControl6.Text = "BELGE SİC NO";
            this.labelControl5.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labelControl5.Location = new Point(0x110, 0x13e);
            this.labelControl5.Name = "labelControl5";
            this.labelControl5.Size = new Size(0x7d, 15);
            this.labelControl5.StyleController = this.layoutControl2;
            this.labelControl5.TabIndex = 0x16;
            this.labelControl5.Text = "ODA SİCİL NO";
            this.labelControl4.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labelControl4.Location = new Point(0x7f, 0x13e);
            this.labelControl4.Name = "labelControl4";
            this.labelControl4.Size = new Size(0x8d, 15);
            this.labelControl4.StyleController = this.layoutControl2;
            this.labelControl4.TabIndex = 0x15;
            this.labelControl4.Text = "ADI SOYADI";
            this.labelControl3.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labelControl3.Location = new Point(7, 0x13e);
            this.labelControl3.Name = "labelControl3";
            this.labelControl3.Size = new Size(0x74, 15);
            this.labelControl3.StyleController = this.layoutControl2;
            this.labelControl3.TabIndex = 20;
            this.labelControl3.Text = "\x00dcNVAN";
            this.labelControl2.Location = new Point(7, 0x12d);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new Size(0x289, 13);
            this.labelControl2.StyleController = this.layoutControl2;
            this.labelControl2.TabIndex = 0x13;
            this.labelControl1.Location = new Point(7, 0xce);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new Size(0x289, 13);
            this.labelControl1.StyleController = this.layoutControl2;
            this.labelControl1.TabIndex = 0x12;
            this.textEdit11.EnterMoveNextControl = true;
            this.textEdit11.Location = new Point(0x1ec, 0x113);
            this.textEdit11.Name = "textEdit11";
            this.textEdit11.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textEdit11.Properties.Appearance.Options.UseFont = true;
            this.textEdit11.Size = new Size(0xa4, 0x16);
            this.textEdit11.StyleController = this.layoutControl2;
            this.textEdit11.TabIndex = 0x10;
            this.dateEdit2.EditValue = null;
            this.dateEdit2.EnterMoveNextControl = true;
            this.dateEdit2.Location = new Point(0xaf, 0x113);
            this.dateEdit2.Name = "dateEdit2";
            this.dateEdit2.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.dateEdit2.Properties.Appearance.Options.UseFont = true;
            EditorButton[] buttons = new EditorButton[] { new EditorButton(ButtonPredefines.Combo) };
            this.dateEdit2.Properties.Buttons.AddRange(buttons);
            EditorButton[] buttonArray2 = new EditorButton[] { new EditorButton() };
            this.dateEdit2.Properties.CalendarTimeProperties.Buttons.AddRange(buttonArray2);
            this.dateEdit2.Size = new Size(0x91, 0x16);
            this.dateEdit2.StyleController = this.layoutControl2;
            this.dateEdit2.TabIndex = 15;
            this.textEdit10.EnterMoveNextControl = true;
            this.textEdit10.Location = new Point(0x1ec, 0xf9);
            this.textEdit10.Name = "textEdit10";
            this.textEdit10.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textEdit10.Properties.Appearance.Options.UseFont = true;
            this.textEdit10.Size = new Size(0xa4, 0x16);
            this.textEdit10.StyleController = this.layoutControl2;
            this.textEdit10.TabIndex = 14;
            this.dateEdit1.EditValue = null;
            this.dateEdit1.EnterMoveNextControl = true;
            this.dateEdit1.Location = new Point(0xaf, 0xf9);
            this.dateEdit1.Name = "dateEdit1";
            this.dateEdit1.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.dateEdit1.Properties.Appearance.Options.UseFont = true;
            EditorButton[] buttonArray3 = new EditorButton[] { new EditorButton(ButtonPredefines.Combo) };
            this.dateEdit1.Properties.Buttons.AddRange(buttonArray3);
            EditorButton[] buttonArray4 = new EditorButton[] { new EditorButton() };
            this.dateEdit1.Properties.CalendarTimeProperties.Buttons.AddRange(buttonArray4);
            this.dateEdit1.Size = new Size(0x91, 0x16);
            this.dateEdit1.StyleController = this.layoutControl2;
            this.dateEdit1.TabIndex = 13;
            this.textEdit9.EnterMoveNextControl = true;
            this.textEdit9.Location = new Point(0x1ec, 0xdf);
            this.textEdit9.Name = "textEdit9";
            this.textEdit9.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textEdit9.Properties.Appearance.Options.UseFont = true;
            this.textEdit9.Size = new Size(0xa4, 0x16);
            this.textEdit9.StyleController = this.layoutControl2;
            this.textEdit9.TabIndex = 12;
            this.textEdit8.EnterMoveNextControl = true;
            this.textEdit8.Location = new Point(0xaf, 0xdf);
            this.textEdit8.Name = "textEdit8";
            this.textEdit8.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textEdit8.Properties.Appearance.Options.UseFont = true;
            this.textEdit8.Size = new Size(0x91, 0x16);
            this.textEdit8.StyleController = this.layoutControl2;
            this.textEdit8.TabIndex = 11;
            this.textBox2.Enabled = false;
            this.textBox2.EnterMoveNextControl = true;
            this.textBox2.Location = new Point(0xb1, 180);
            this.textBox2.Name = "textBox2";
            this.textBox2.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textBox2.Properties.Appearance.Options.UseFont = true;
            this.textBox2.Size = new Size(0x1df, 0x16);
            this.textBox2.StyleController = this.layoutControl2;
            this.textBox2.TabIndex = 10;
            this.label1.Appearance.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.label1.Appearance.TextOptions.HAlignment = HorzAlignment.Center;
            this.label1.Location = new Point(180, 7);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x12e, 13);
            this.label1.StyleController = this.layoutControl2;
            this.label1.TabIndex = 4;
            this.label1.Text = "TEKNİK DOSYA İ\x00c7İN FİRMA BİLGİLERİNİ GİRİNİZ...";
            this.textBox6.Enabled = false;
            this.textBox6.EnterMoveNextControl = true;
            this.textBox6.Location = new Point(0xb1, 0x4c);
            this.textBox6.Name = "textBox6";
            this.textBox6.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textBox6.Properties.Appearance.Options.UseFont = true;
            this.textBox6.Size = new Size(0x1df, 0x16);
            this.textBox6.StyleController = this.layoutControl2;
            this.textBox6.TabIndex = 9;
            this.textEdit5.Enabled = false;
            this.textEdit5.EnterMoveNextControl = true;
            this.textEdit5.Location = new Point(0xb1, 0x66);
            this.textEdit5.Name = "textEdit5";
            this.textEdit5.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textEdit5.Properties.Appearance.Options.UseFont = true;
            this.textEdit5.Size = new Size(0x1df, 0x16);
            this.textEdit5.StyleController = this.layoutControl2;
            this.textEdit5.TabIndex = 8;
            this.textBox3.Enabled = false;
            this.textBox3.EnterMoveNextControl = true;
            this.textBox3.Location = new Point(0xb1, 0x9a);
            this.textBox3.Name = "textBox3";
            this.textBox3.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textBox3.Properties.Appearance.Options.UseFont = true;
            this.textBox3.Size = new Size(0x1df, 0x16);
            this.textBox3.StyleController = this.layoutControl2;
            this.textBox3.TabIndex = 7;
            this.textBox5.Enabled = false;
            this.textBox5.EnterMoveNextControl = true;
            this.textBox5.Location = new Point(0xb1, 0x80);
            this.textBox5.Name = "textBox5";
            this.textBox5.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textBox5.Properties.Appearance.Options.UseFont = true;
            this.textBox5.Properties.Mask.EditMask = "0(999)000-00 00";
            this.textBox5.Properties.Mask.MaskType = MaskType.Simple;
            this.textBox5.Size = new Size(0x1df, 0x16);
            this.textBox5.StyleController = this.layoutControl2;
            this.textBox5.TabIndex = 6;
            this.textBox4.Enabled = false;
            this.textBox4.EnterMoveNextControl = true;
            this.textBox4.Location = new Point(0xb1, 50);
            this.textBox4.Name = "textBox4";
            this.textBox4.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textBox4.Properties.Appearance.Options.UseFont = true;
            this.textBox4.Properties.Mask.EditMask = "0(999)000-00 00";
            this.textBox4.Properties.Mask.MaskType = MaskType.Simple;
            this.textBox4.Size = new Size(0x1df, 0x16);
            this.textBox4.StyleController = this.layoutControl2;
            this.textBox4.TabIndex = 5;
            this.textBox1.Enabled = false;
            this.textBox1.EnterMoveNextControl = true;
            this.textBox1.Location = new Point(0xb1, 0x18);
            this.textBox1.Name = "textBox1";
            this.textBox1.Properties.Appearance.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.textBox1.Properties.Appearance.Options.UseFont = true;
            this.textBox1.Size = new Size(0x1df, 0x16);
            this.textBox1.StyleController = this.layoutControl2;
            this.textBox1.TabIndex = 4;
            this.layoutControlGroup2.CustomizationFormText = "layoutControlGroup2";
            this.layoutControlGroup2.EnableIndentsWithoutBorders = DefaultBoolean.True;
            this.layoutControlGroup2.GroupBordersVisible = false;
            BaseLayoutItem[] items = new BaseLayoutItem[] { 
                this.layoutControlItem15, this.layoutControlItem25, this.layoutControlItem26, this.layoutControlItem5, this.layoutControlItem22, this.layoutControlItem23, this.layoutControlItem24, this.layoutControlItem27, this.layoutControlItem21, this.layoutControlItem6, this.layoutControlItem16, this.layoutControlItem20, this.layoutControlItem1, this.layoutControlItem2, this.layoutControlItem3, this.layoutControlItem4,
                this.layoutControlItem7, this.layoutControlItem8, this.layoutControlItem9, this.layoutControlItem10, this.layoutControlItem11, this.layoutControlItem12, this.layoutControlItem13, this.layoutControlItem14, this.layoutControlItem28, this.layoutControlItem29, this.layoutControlItem30, this.layoutControlItem31, this.layoutControlItem32, this.layoutControlItem19, this.layoutControlItem17, this.layoutControlItem18
            };
            this.layoutControlGroup2.Items.AddRange(items);
            this.layoutControlGroup2.Location = new Point(0, 0);
            this.layoutControlGroup2.Name = "Root";
            this.layoutControlGroup2.Padding = new DevExpress.XtraLayout.Utils.Padding(5, 5, 5, 5);
            this.layoutControlGroup2.Size = new Size(0x297, 0x1b2);
            this.layoutControlGroup2.TextVisible = false;
            this.layoutControlItem15.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem15.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem15.Control = this.textBox1;
            this.layoutControlItem15.CustomizationFormText = "Firma Adı :";
            this.layoutControlItem15.Location = new Point(0, 0x11);
            this.layoutControlItem15.Name = "layoutControlItem15";
            this.layoutControlItem15.Size = new Size(0x28d, 0x1a);
            this.layoutControlItem15.Text = "Firma Adı :";
            this.layoutControlItem15.TextAlignMode = TextAlignModeItem.CustomSize;
            this.layoutControlItem15.TextSize = new Size(0xa5, 0);
            this.layoutControlItem15.TextToControlDistance = 5;
            this.layoutControlItem25.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem25.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem25.Control = this.textEdit10;
            this.layoutControlItem25.CustomizationFormText = "Sanayi Sicil Belge No :";
            this.layoutControlItem25.Location = new Point(0x13d, 0xf2);
            this.layoutControlItem25.Name = "layoutControlItem25";
            this.layoutControlItem25.Size = new Size(0x150, 0x1a);
            this.layoutControlItem25.Text = "Sanayi Sicil Belge No :";
            this.layoutControlItem25.TextSize = new Size(0xa5, 15);
            this.layoutControlItem26.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem26.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem26.Control = this.dateEdit2;
            this.layoutControlItem26.CustomizationFormText = "HYB Belge Tarihi :";
            this.layoutControlItem26.Location = new Point(0, 0x10c);
            this.layoutControlItem26.Name = "layoutControlItem26";
            this.layoutControlItem26.Size = new Size(0x13d, 0x1a);
            this.layoutControlItem26.Text = "HYB Belge Tarihi :";
            this.layoutControlItem26.TextSize = new Size(0xa5, 15);
            this.layoutControlItem5.Control = this.button1;
            this.layoutControlItem5.CustomizationFormText = "layoutControlItem5";
            this.layoutControlItem5.Location = new Point(0, 0x17e);
            this.layoutControlItem5.MaxSize = new Size(0, 0x2a);
            this.layoutControlItem5.MinSize = new Size(0x36, 0x2a);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Size = new Size(0x28d, 0x2a);
            this.layoutControlItem5.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem5.TextSize = new Size(0, 0);
            this.layoutControlItem5.TextVisible = false;
            this.layoutControlItem22.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem22.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem22.Control = this.textEdit8;
            this.layoutControlItem22.CustomizationFormText = "Onaylayan Kuruluş Adı :";
            this.layoutControlItem22.Location = new Point(0, 0xd8);
            this.layoutControlItem22.Name = "layoutControlItem22";
            this.layoutControlItem22.Size = new Size(0x13d, 0x1a);
            this.layoutControlItem22.Text = "Onaylayan Kuruluş Adı :";
            this.layoutControlItem22.TextSize = new Size(0xa5, 15);
            this.layoutControlItem23.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem23.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem23.Control = this.textEdit9;
            this.layoutControlItem23.CustomizationFormText = "Onaylayan Kuruluş No :";
            this.layoutControlItem23.Location = new Point(0x13d, 0xd8);
            this.layoutControlItem23.Name = "layoutControlItem23";
            this.layoutControlItem23.Size = new Size(0x150, 0x1a);
            this.layoutControlItem23.Text = "Onaylayan Kuruluş No :";
            this.layoutControlItem23.TextSize = new Size(0xa5, 15);
            this.layoutControlItem18.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem18.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem18.Control = this.textBox3;
            this.layoutControlItem18.CustomizationFormText = "Firma Yetkili :";
            this.layoutControlItem18.Location = new Point(0, 0x93);
            this.layoutControlItem18.Name = "layoutControlItem18";
            this.layoutControlItem18.Size = new Size(0x28d, 0x1a);
            this.layoutControlItem18.Text = "Firma Yetkili :";
            this.layoutControlItem18.TextAlignMode = TextAlignModeItem.CustomSize;
            this.layoutControlItem18.TextSize = new Size(0xa5, 0);
            this.layoutControlItem18.TextToControlDistance = 5;
            this.layoutControlItem24.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem24.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem24.Control = this.dateEdit1;
            this.layoutControlItem24.CustomizationFormText = "Sanayi Sicil Belge Tarihi :";
            this.layoutControlItem24.Location = new Point(0, 0xf2);
            this.layoutControlItem24.Name = "layoutControlItem24";
            this.layoutControlItem24.Size = new Size(0x13d, 0x1a);
            this.layoutControlItem24.Text = "Sanayi Sicil Belge Tarihi :";
            this.layoutControlItem24.TextSize = new Size(0xa5, 15);
            this.layoutControlItem27.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem27.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem27.Control = this.textEdit11;
            this.layoutControlItem27.CustomizationFormText = "HYB BELGE NO :";
            this.layoutControlItem27.Location = new Point(0x13d, 0x10c);
            this.layoutControlItem27.Name = "layoutControlItem27";
            this.layoutControlItem27.Size = new Size(0x150, 0x1a);
            this.layoutControlItem27.Text = "HYB Belge No :";
            this.layoutControlItem27.TextSize = new Size(0xa5, 15);
            this.layoutControlItem21.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem21.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem21.Control = this.textBox2;
            this.layoutControlItem21.CustomizationFormText = "Firma Adresi :";
            this.layoutControlItem21.Location = new Point(0, 0xad);
            this.layoutControlItem21.Name = "layoutControlItem21";
            this.layoutControlItem21.Size = new Size(0x28d, 0x1a);
            this.layoutControlItem21.Text = "Firma Adresi :";
            this.layoutControlItem21.TextAlignMode = TextAlignModeItem.CustomSize;
            this.layoutControlItem21.TextSize = new Size(0xa5, 0);
            this.layoutControlItem21.TextToControlDistance = 5;
            this.layoutControlItem6.Control = this.labelControl1;
            this.layoutControlItem6.CustomizationFormText = "layoutControlItem6";
            this.layoutControlItem6.Location = new Point(0, 0xc7);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Size = new Size(0x28d, 0x11);
            this.layoutControlItem6.TextSize = new Size(0, 0);
            this.layoutControlItem6.TextVisible = false;
            this.layoutControlItem19.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem19.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem19.Control = this.textEdit5;
            this.layoutControlItem19.CustomizationFormText = "Firma Marka :";
            this.layoutControlItem19.Location = new Point(0, 0x5f);
            this.layoutControlItem19.Name = "layoutControlItem19";
            this.layoutControlItem19.Size = new Size(0x28d, 0x1a);
            this.layoutControlItem19.Text = "Firma Marka :";
            this.layoutControlItem19.TextAlignMode = TextAlignModeItem.CustomSize;
            this.layoutControlItem19.TextSize = new Size(0xa5, 15);
            this.layoutControlItem19.TextToControlDistance = 5;
            this.layoutControlItem16.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem16.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem16.Control = this.textBox4;
            this.layoutControlItem16.CustomizationFormText = "Firma Tel :";
            this.layoutControlItem16.Location = new Point(0, 0x2b);
            this.layoutControlItem16.Name = "layoutControlItem16";
            this.layoutControlItem16.Size = new Size(0x28d, 0x1a);
            this.layoutControlItem16.Text = "Firma Tel :";
            this.layoutControlItem16.TextAlignMode = TextAlignModeItem.CustomSize;
            this.layoutControlItem16.TextSize = new Size(0xa5, 15);
            this.layoutControlItem16.TextToControlDistance = 5;
            this.layoutControlItem20.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem20.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem20.Control = this.textBox6;
            this.layoutControlItem20.CustomizationFormText = "Firma Mail :";
            this.layoutControlItem20.Location = new Point(0, 0x45);
            this.layoutControlItem20.Name = "layoutControlItem20";
            this.layoutControlItem20.Size = new Size(0x28d, 0x1a);
            this.layoutControlItem20.Text = "Firma Mail :";
            this.layoutControlItem20.TextAlignMode = TextAlignModeItem.CustomSize;
            this.layoutControlItem20.TextSize = new Size(0xa5, 15);
            this.layoutControlItem20.TextToControlDistance = 5;
            this.layoutControlItem17.AppearanceItemCaption.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.layoutControlItem17.AppearanceItemCaption.Options.UseFont = true;
            this.layoutControlItem17.Control = this.textBox5;
            this.layoutControlItem17.CustomizationFormText = "Firma Fax :";
            this.layoutControlItem17.Location = new Point(0, 0x79);
            this.layoutControlItem17.Name = "layoutControlItem17";
            this.layoutControlItem17.Size = new Size(0x28d, 0x1a);
            this.layoutControlItem17.Text = "Firma Fax :";
            this.layoutControlItem17.TextAlignMode = TextAlignModeItem.CustomSize;
            this.layoutControlItem17.TextSize = new Size(0xa5, 0);
            this.layoutControlItem17.TextToControlDistance = 5;
            this.layoutControlItem1.Control = this.label1;
            this.layoutControlItem1.ControlAlignment = ContentAlignment.TopCenter;
            this.layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            this.layoutControlItem1.Location = new Point(0, 0);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new Size(0x28d, 0x11);
            this.layoutControlItem1.TextSize = new Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            this.layoutControlItem2.Control = this.labelControl2;
            this.layoutControlItem2.CustomizationFormText = "layoutControlItem2";
            this.layoutControlItem2.Location = new Point(0, 0x126);
            this.layoutControlItem2.MaxSize = new Size(0, 0x11);
            this.layoutControlItem2.MinSize = new Size(0x43, 0x11);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new Size(0x28d, 0x11);
            this.layoutControlItem2.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem2.TextSize = new Size(0, 0);
            this.layoutControlItem2.TextVisible = false;
            this.layoutControlItem3.Control = this.labelControl3;
            this.layoutControlItem3.CustomizationFormText = "layoutControlItem3";
            this.layoutControlItem3.Location = new Point(0, 0x137);
            this.layoutControlItem3.MaxSize = new Size(120, 0x1a);
            this.layoutControlItem3.MinSize = new Size(0x26, 0x11);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new Size(120, 0x13);
            this.layoutControlItem3.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem3.TextSize = new Size(0, 0);
            this.layoutControlItem3.TextVisible = false;
            this.layoutControlItem4.Control = this.labelControl4;
            this.layoutControlItem4.CustomizationFormText = "layoutControlItem4";
            this.layoutControlItem4.Location = new Point(120, 0x137);
            this.layoutControlItem4.MaxSize = new Size(190, 0x1a);
            this.layoutControlItem4.MinSize = new Size(0x3f, 0x11);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Size = new Size(0x91, 0x13);
            this.layoutControlItem4.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem4.TextSize = new Size(0, 0);
            this.layoutControlItem4.TextVisible = false;
            this.layoutControlItem7.Control = this.labelControl5;
            this.layoutControlItem7.CustomizationFormText = "layoutControlItem7";
            this.layoutControlItem7.Location = new Point(0x109, 0x137);
            this.layoutControlItem7.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem7.MinSize = new Size(0x49, 0x11);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Size = new Size(0x81, 0x13);
            this.layoutControlItem7.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem7.TextSize = new Size(0, 0);
            this.layoutControlItem7.TextVisible = false;
            this.layoutControlItem8.Control = this.labelControl6;
            this.layoutControlItem8.CustomizationFormText = "layoutControlItem8";
            this.layoutControlItem8.Location = new Point(0x18a, 0x137);
            this.layoutControlItem8.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem8.MinSize = new Size(0x3f, 0x11);
            this.layoutControlItem8.Name = "layoutControlItem8";
            this.layoutControlItem8.Size = new Size(130, 0x13);
            this.layoutControlItem8.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem8.TextSize = new Size(0, 0);
            this.layoutControlItem8.TextVisible = false;
            this.layoutControlItem9.Control = this.labelControl7;
            this.layoutControlItem9.CustomizationFormText = "layoutControlItem9";
            this.layoutControlItem9.Location = new Point(0x20c, 0x137);
            this.layoutControlItem9.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem9.MinSize = new Size(0x4d, 0x11);
            this.layoutControlItem9.Name = "layoutControlItem9";
            this.layoutControlItem9.Size = new Size(0x81, 0x13);
            this.layoutControlItem9.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem9.TextSize = new Size(0, 0);
            this.layoutControlItem9.TextVisible = false;
            this.layoutControlItem10.Control = this.labelControl8;
            this.layoutControlItem10.CustomizationFormText = "layoutControlItem10";
            this.layoutControlItem10.Location = new Point(0, 330);
            this.layoutControlItem10.MaxSize = new Size(120, 0x1a);
            this.layoutControlItem10.MinSize = new Size(120, 0x11);
            this.layoutControlItem10.Name = "layoutControlItem10";
            this.layoutControlItem10.Size = new Size(120, 0x1a);
            this.layoutControlItem10.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem10.TextSize = new Size(0, 0);
            this.layoutControlItem10.TextVisible = false;
            this.layoutControlItem11.Control = this.labelControl9;
            this.layoutControlItem11.CustomizationFormText = "layoutControlItem11";
            this.layoutControlItem11.Location = new Point(0, 0x164);
            this.layoutControlItem11.MaxSize = new Size(120, 0x1a);
            this.layoutControlItem11.MinSize = new Size(0x43, 0x11);
            this.layoutControlItem11.Name = "layoutControlItem11";
            this.layoutControlItem11.Size = new Size(120, 0x1a);
            this.layoutControlItem11.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem11.TextSize = new Size(0, 0);
            this.layoutControlItem11.TextVisible = false;
            this.layoutControlItem12.Control = this.mmad;
            this.layoutControlItem12.CustomizationFormText = "layoutControlItem12";
            this.layoutControlItem12.Location = new Point(120, 330);
            this.layoutControlItem12.MaxSize = new Size(190, 0x1a);
            this.layoutControlItem12.MinSize = new Size(120, 0x18);
            this.layoutControlItem12.Name = "layoutControlItem12";
            this.layoutControlItem12.Size = new Size(0x91, 0x1a);
            this.layoutControlItem12.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem12.TextSize = new Size(0, 0);
            this.layoutControlItem12.TextVisible = false;
            this.layoutControlItem13.Control = this.mmoda;
            this.layoutControlItem13.CustomizationFormText = "layoutControlItem13";
            this.layoutControlItem13.Location = new Point(0x109, 330);
            this.layoutControlItem13.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem13.MinSize = new Size(120, 0x18);
            this.layoutControlItem13.Name = "layoutControlItem13";
            this.layoutControlItem13.Size = new Size(0x81, 0x1a);
            this.layoutControlItem13.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem13.TextSize = new Size(0, 0);
            this.layoutControlItem13.TextVisible = false;
            this.layoutControlItem14.Control = this.mmbel;
            this.layoutControlItem14.CustomizationFormText = "layoutControlItem14";
            this.layoutControlItem14.Location = new Point(0x18a, 330);
            this.layoutControlItem14.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem14.MinSize = new Size(0x36, 0x1a);
            this.layoutControlItem14.Name = "layoutControlItem14";
            this.layoutControlItem14.Size = new Size(130, 0x1a);
            this.layoutControlItem14.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem14.TextSize = new Size(0, 0);
            this.layoutControlItem14.TextVisible = false;
            this.layoutControlItem28.Control = this.mmsmm;
            this.layoutControlItem28.CustomizationFormText = "layoutControlItem28";
            this.layoutControlItem28.Location = new Point(0x20c, 330);
            this.layoutControlItem28.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem28.MinSize = new Size(0x36, 0x18);
            this.layoutControlItem28.Name = "layoutControlItem28";
            this.layoutControlItem28.Size = new Size(0x81, 0x1a);
            this.layoutControlItem28.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem28.TextSize = new Size(0, 0);
            this.layoutControlItem28.TextVisible = false;
            this.layoutControlItem29.Control = this.emad;
            this.layoutControlItem29.CustomizationFormText = "layoutControlItem29";
            this.layoutControlItem29.Location = new Point(120, 0x164);
            this.layoutControlItem29.MaxSize = new Size(190, 0x1a);
            this.layoutControlItem29.MinSize = new Size(0x36, 0x18);
            this.layoutControlItem29.Name = "layoutControlItem29";
            this.layoutControlItem29.Size = new Size(0x91, 0x1a);
            this.layoutControlItem29.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem29.TextSize = new Size(0, 0);
            this.layoutControlItem29.TextVisible = false;
            this.layoutControlItem30.Control = this.emoda;
            this.layoutControlItem30.CustomizationFormText = "layoutControlItem30";
            this.layoutControlItem30.Location = new Point(0x109, 0x164);
            this.layoutControlItem30.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem30.MinSize = new Size(120, 0x18);
            this.layoutControlItem30.Name = "layoutControlItem30";
            this.layoutControlItem30.Size = new Size(0x81, 0x1a);
            this.layoutControlItem30.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem30.TextSize = new Size(0, 0);
            this.layoutControlItem30.TextVisible = false;
            this.layoutControlItem31.Control = this.embel;
            this.layoutControlItem31.CustomizationFormText = "layoutControlItem31";
            this.layoutControlItem31.Location = new Point(0x18a, 0x164);
            this.layoutControlItem31.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem31.MinSize = new Size(0x36, 0x18);
            this.layoutControlItem31.Name = "layoutControlItem31";
            this.layoutControlItem31.Size = new Size(130, 0x1a);
            this.layoutControlItem31.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem31.TextSize = new Size(0, 0);
            this.layoutControlItem31.TextVisible = false;
            this.layoutControlItem32.Control = this.emsmm;
            this.layoutControlItem32.CustomizationFormText = "layoutControlItem32";
            this.layoutControlItem32.Location = new Point(0x20c, 0x164);
            this.layoutControlItem32.MaxSize = new Size(150, 0x1a);
            this.layoutControlItem32.MinSize = new Size(120, 0x18);
            this.layoutControlItem32.Name = "layoutControlItem32";
            this.layoutControlItem32.Size = new Size(0x81, 0x1a);
            this.layoutControlItem32.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem32.TextSize = new Size(0, 0);
            this.layoutControlItem32.TextVisible = false;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x297, 0x1b2);
            base.Controls.Add(this.layoutControl2);
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "FirmaBilgileri";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FİRMA GİRİŞİ";
            base.Load += new EventHandler(this.FirmaBilgileri_Load);
            this.layoutControl2.EndInit();
            this.layoutControl2.ResumeLayout(false);
            this.emsmm.Properties.EndInit();
            this.embel.Properties.EndInit();
            this.emoda.Properties.EndInit();
            this.emad.Properties.EndInit();
            this.mmsmm.Properties.EndInit();
            this.mmbel.Properties.EndInit();
            this.mmoda.Properties.EndInit();
            this.mmad.Properties.EndInit();
            this.textEdit11.Properties.EndInit();
            this.dateEdit2.Properties.CalendarTimeProperties.EndInit();
            this.dateEdit2.Properties.EndInit();
            this.textEdit10.Properties.EndInit();
            this.dateEdit1.Properties.CalendarTimeProperties.EndInit();
            this.dateEdit1.Properties.EndInit();
            this.textEdit9.Properties.EndInit();
            this.textEdit8.Properties.EndInit();
            this.textBox2.Properties.EndInit();
            this.textBox6.Properties.EndInit();
            this.textEdit5.Properties.EndInit();
            this.textBox3.Properties.EndInit();
            this.textBox5.Properties.EndInit();
            this.textBox4.Properties.EndInit();
            this.textBox1.Properties.EndInit();
            this.layoutControlGroup2.EndInit();
            this.layoutControlItem15.EndInit();
            this.layoutControlItem25.EndInit();
            this.layoutControlItem26.EndInit();
            this.layoutControlItem5.EndInit();
            this.layoutControlItem22.EndInit();
            this.layoutControlItem23.EndInit();
            this.layoutControlItem18.EndInit();
            this.layoutControlItem24.EndInit();
            this.layoutControlItem27.EndInit();
            this.layoutControlItem21.EndInit();
            this.layoutControlItem6.EndInit();
            this.layoutControlItem19.EndInit();
            this.layoutControlItem16.EndInit();
            this.layoutControlItem20.EndInit();
            this.layoutControlItem17.EndInit();
            this.layoutControlItem1.EndInit();
            this.layoutControlItem2.EndInit();
            this.layoutControlItem3.EndInit();
            this.layoutControlItem4.EndInit();
            this.layoutControlItem7.EndInit();
            this.layoutControlItem8.EndInit();
            this.layoutControlItem9.EndInit();
            this.layoutControlItem10.EndInit();
            this.layoutControlItem11.EndInit();
            this.layoutControlItem12.EndInit();
            this.layoutControlItem13.EndInit();
            this.layoutControlItem14.EndInit();
            this.layoutControlItem28.EndInit();
            this.layoutControlItem29.EndInit();
            this.layoutControlItem30.EndInit();
            this.layoutControlItem31.EndInit();
            this.layoutControlItem32.EndInit();
            base.ResumeLayout(false);
        }
    }
}

