namespace ascad
{
    using DevExpress.Data;
    using DevExpress.Utils;
    using DevExpress.XtraEditors;
    using DevExpress.XtraEditors.Controls;
    using DevExpress.XtraGrid;
    using DevExpress.XtraGrid.Columns;
    using DevExpress.XtraGrid.Views.Base;
    using DevExpress.XtraGrid.Views.Grid;
    using DevExpress.XtraLayout;
    using DevExpress.XtraLayout.Utils;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class tsestandart : Form
    {
        private IContainer components = null;
        private GridColumn gridColumn1;
        private GridColumn gridColumn2;
        private GridColumn gridColumn3;
        private GridColumn gridColumn4;
        private GridColumn gridColumn5;
        private GridControl gridcontroltsecizelge;
        private GridView gridviewtsecizelge;
        private TextEdit kabinalan;
        private TextEdit kabinder;
        public string kabinderstr;
        private TextEdit kabingen;
        public string kabingenstr;
        private Label label1;
        private LabelControl labeltsecizelge6;
        private LabelControl labeltsecizelge8;
        private LayoutControlItem labeltsekabinalan;
        private LayoutControlItem labeltsekabinder;
        private LayoutControlItem labeltsekabingen;
        private LabelControl labeltsem2;
        private LabelControl labeltsemm;
        private LabelControl labeltsemm2;
        private LayoutControl layoutControl1;
        private LayoutControlGroup layoutControlGroup1;
        private LayoutControlItem layoutControlItem1;
        private LayoutControlItem layoutControlItem2;
        private LayoutControlItem layoutControlItem3;
        private LayoutControlItem layoutControlItem4;
        private LayoutControlItem layoutControlItem5;
        private LayoutControlItem layoutControlItem6;
        private LayoutControlItem layoutControlItem7;
        private LayoutControlItem layoutControlItem8;
        private SimpleButton simpleButton1;
        private abc1 xx = new abc1();

        public tsestandart()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components > null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(tsestandart));
            this.gridColumn4 = new GridColumn();
            this.gridColumn3 = new GridColumn();
            this.gridColumn5 = new GridColumn();
            this.layoutControl1 = new LayoutControl();
            this.simpleButton1 = new SimpleButton();
            this.label1 = new Label();
            this.labeltsecizelge6 = new LabelControl();
            this.labeltsem2 = new LabelControl();
            this.labeltsemm2 = new LabelControl();
            this.labeltsecizelge8 = new LabelControl();
            this.labeltsemm = new LabelControl();
            this.gridcontroltsecizelge = new GridControl();
            this.gridviewtsecizelge = new GridView();
            this.gridColumn1 = new GridColumn();
            this.gridColumn2 = new GridColumn();
            this.kabinalan = new TextEdit();
            this.kabinder = new TextEdit();
            this.kabingen = new TextEdit();
            this.layoutControlGroup1 = new LayoutControlGroup();
            this.labeltsekabingen = new LayoutControlItem();
            this.layoutControlItem5 = new LayoutControlItem();
            this.layoutControlItem6 = new LayoutControlItem();
            this.layoutControlItem1 = new LayoutControlItem();
            this.layoutControlItem3 = new LayoutControlItem();
            this.labeltsekabinder = new LayoutControlItem();
            this.layoutControlItem4 = new LayoutControlItem();
            this.labeltsekabinalan = new LayoutControlItem();
            this.layoutControlItem7 = new LayoutControlItem();
            this.layoutControlItem8 = new LayoutControlItem();
            this.layoutControlItem2 = new LayoutControlItem();
            this.layoutControl1.BeginInit();
            this.layoutControl1.SuspendLayout();
            this.gridcontroltsecizelge.BeginInit();
            this.gridviewtsecizelge.BeginInit();
            this.kabinalan.Properties.BeginInit();
            this.kabinder.Properties.BeginInit();
            this.kabingen.Properties.BeginInit();
            this.layoutControlGroup1.BeginInit();
            this.labeltsekabingen.BeginInit();
            this.layoutControlItem5.BeginInit();
            this.layoutControlItem6.BeginInit();
            this.layoutControlItem1.BeginInit();
            this.layoutControlItem3.BeginInit();
            this.labeltsekabinder.BeginInit();
            this.layoutControlItem4.BeginInit();
            this.labeltsekabinalan.BeginInit();
            this.layoutControlItem7.BeginInit();
            this.layoutControlItem8.BeginInit();
            this.layoutControlItem2.BeginInit();
            base.SuspendLayout();
            this.gridColumn4.AppearanceCell.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridColumn4.AppearanceCell.Options.UseFont = true;
            this.gridColumn4.AppearanceCell.Options.UseTextOptions = true;
            this.gridColumn4.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn4.AppearanceHeader.Font = new Font("Tahoma", 9f, FontStyle.Bold);
            this.gridColumn4.AppearanceHeader.ForeColor = Color.Maroon;
            this.gridColumn4.AppearanceHeader.Options.UseFont = true;
            this.gridColumn4.AppearanceHeader.Options.UseForeColor = true;
            this.gridColumn4.AppearanceHeader.Options.UseTextOptions = true;
            this.gridColumn4.AppearanceHeader.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn4.Caption = "\x00c7izelge 6";
            this.gridColumn4.DisplayFormat.FormatString = "N2";
            this.gridColumn4.DisplayFormat.FormatType = FormatType.Numeric;
            this.gridColumn4.FieldName = "cizelge6";
            this.gridColumn4.Name = "gridColumn4";
            this.gridColumn4.OptionsColumn.AllowEdit = false;
            this.gridColumn4.UnboundType = UnboundColumnType.Decimal;
            this.gridColumn4.Visible = true;
            this.gridColumn4.VisibleIndex = 3;
            this.gridColumn4.Width = 0x9b;
            this.gridColumn3.AppearanceCell.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridColumn3.AppearanceCell.Options.UseFont = true;
            this.gridColumn3.AppearanceCell.Options.UseTextOptions = true;
            this.gridColumn3.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn3.AppearanceHeader.Font = new Font("Tahoma", 9f, FontStyle.Bold);
            this.gridColumn3.AppearanceHeader.ForeColor = Color.Maroon;
            this.gridColumn3.AppearanceHeader.Options.UseFont = true;
            this.gridColumn3.AppearanceHeader.Options.UseForeColor = true;
            this.gridColumn3.AppearanceHeader.Options.UseTextOptions = true;
            this.gridColumn3.AppearanceHeader.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn3.Caption = "\x00c7izelge 8";
            this.gridColumn3.DisplayFormat.FormatString = "N2";
            this.gridColumn3.DisplayFormat.FormatType = FormatType.Numeric;
            this.gridColumn3.FieldName = "cizelge8";
            this.gridColumn3.Name = "gridColumn3";
            this.gridColumn3.OptionsColumn.AllowEdit = false;
            this.gridColumn3.UnboundType = UnboundColumnType.Decimal;
            this.gridColumn3.Visible = true;
            this.gridColumn3.VisibleIndex = 2;
            this.gridColumn3.Width = 0xd8;
            this.gridColumn5.AppearanceCell.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridColumn5.AppearanceCell.Options.UseFont = true;
            this.gridColumn5.AppearanceCell.Options.UseTextOptions = true;
            this.gridColumn5.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn5.AppearanceHeader.Font = new Font("Tahoma", 9f, FontStyle.Bold);
            this.gridColumn5.AppearanceHeader.ForeColor = Color.Maroon;
            this.gridColumn5.AppearanceHeader.Options.UseFont = true;
            this.gridColumn5.AppearanceHeader.Options.UseForeColor = true;
            this.gridColumn5.AppearanceHeader.Options.UseTextOptions = true;
            this.gridColumn5.AppearanceHeader.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn5.Caption = "\x00c7izelge 7";
            this.gridColumn5.DisplayFormat.FormatString = "N2";
            this.gridColumn5.DisplayFormat.FormatType = FormatType.Numeric;
            this.gridColumn5.FieldName = "cizelge7";
            this.gridColumn5.Name = "gridColumn5";
            this.gridColumn5.OptionsColumn.AllowEdit = false;
            this.gridColumn5.UnboundType = UnboundColumnType.Decimal;
            this.gridColumn5.Width = 0x93;
            this.layoutControl1.Controls.Add(this.simpleButton1);
            this.layoutControl1.Controls.Add(this.label1);
            this.layoutControl1.Controls.Add(this.labeltsecizelge6);
            this.layoutControl1.Controls.Add(this.labeltsem2);
            this.layoutControl1.Controls.Add(this.labeltsemm2);
            this.layoutControl1.Controls.Add(this.labeltsecizelge8);
            this.layoutControl1.Controls.Add(this.labeltsemm);
            this.layoutControl1.Controls.Add(this.gridcontroltsecizelge);
            this.layoutControl1.Controls.Add(this.kabinalan);
            this.layoutControl1.Controls.Add(this.kabinder);
            this.layoutControl1.Controls.Add(this.kabingen);
            this.layoutControl1.Dock = DockStyle.Fill;
            this.layoutControl1.Location = new Point(0, 0);
            this.layoutControl1.Name = "layoutControl1";
            this.layoutControl1.Root = this.layoutControlGroup1;
            this.layoutControl1.Size = new Size(0x2d2, 0x229);
            this.layoutControl1.TabIndex = 0;
            this.layoutControl1.Text = "layoutControl1";
            this.simpleButton1.Location = new Point(0x268, 7);
            this.simpleButton1.Name = "simpleButton1";
            this.simpleButton1.Size = new Size(0x63, 0x16);
            this.simpleButton1.StyleController = this.layoutControl1;
            this.simpleButton1.TabIndex = 0x13;
            this.simpleButton1.Text = "YENİDEN HESAPLA";
            this.simpleButton1.Click += new EventHandler(this.simpleButton1_Click);
            this.label1.FlatStyle = FlatStyle.System;
            this.label1.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.label1.Location = new Point(7, 0x1fc);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x2c4, 20);
            this.label1.TabIndex = 0x12;
            this.label1.Text = manager.GetString("label1.Text");
            this.labeltsecizelge6.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsecizelge6.Appearance.TextOptions.WordWrap = WordWrap.Wrap;
            this.labeltsecizelge6.AutoSizeMode = LabelAutoSizeMode.None;
            this.labeltsecizelge6.Location = new Point(7, 490);
            this.labeltsecizelge6.Name = "labeltsecizelge6";
            this.labeltsecizelge6.Size = new Size(0x2c4, 14);
            this.labeltsecizelge6.StyleController = this.layoutControl1;
            this.labeltsecizelge6.TabIndex = 15;
            this.labeltsecizelge6.Text = "\x00c7izelge 6 : Beyan y\x00fck\x00fc ve kabinin azami kullanılabilir (net) alanı belirtir (2500 kg sonrasında, her bir ilave 100 kg i\x00e7in 0,16 m2 eklenir.)";
            this.labeltsem2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsem2.AutoSizeMode = LabelAutoSizeMode.None;
            this.labeltsem2.Location = new Point(0x24f, 7);
            this.labeltsem2.Name = "labeltsem2";
            this.labeltsem2.Size = new Size(0x15, 13);
            this.labeltsem2.StyleController = this.layoutControl1;
            this.labeltsem2.TabIndex = 11;
            this.labeltsem2.Text = "m2";
            this.labeltsemm2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsemm2.AutoSizeMode = LabelAutoSizeMode.None;
            this.labeltsemm2.Location = new Point(0xb7, 7);
            this.labeltsemm2.Name = "labeltsemm2";
            this.labeltsemm2.Size = new Size(30, 13);
            this.labeltsemm2.StyleController = this.layoutControl1;
            this.labeltsemm2.TabIndex = 10;
            this.labeltsemm2.Text = "mm";
            this.labeltsecizelge8.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsecizelge8.Appearance.TextOptions.WordWrap = WordWrap.Wrap;
            this.labeltsecizelge8.AutoSizeMode = LabelAutoSizeMode.None;
            this.labeltsecizelge8.Location = new Point(7, 0x214);
            this.labeltsecizelge8.Name = "labeltsecizelge8";
            this.labeltsecizelge8.Size = new Size(0x2c4, 14);
            this.labeltsecizelge8.StyleController = this.layoutControl1;
            this.labeltsecizelge8.TabIndex = 0x10;
            this.labeltsecizelge8.Text = "\x00c7izelge 8 : İnsan sayıları ve kabinin asgari kullanılabilir alanı (20 insandan sonra, her bir insan i\x00e7in 0,115 m2 ilave edilir.)";
            this.labeltsemm.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsemm.AutoSizeMode = LabelAutoSizeMode.None;
            this.labeltsemm.Location = new Point(0x195, 7);
            this.labeltsemm.Name = "labeltsemm";
            this.labeltsemm.Size = new Size(0x1a, 20);
            this.labeltsemm.StyleController = this.layoutControl1;
            this.labeltsemm.TabIndex = 9;
            this.labeltsemm.Text = "mm";
            this.gridcontroltsecizelge.Location = new Point(7, 0x2b);
            this.gridcontroltsecizelge.MainView = this.gridviewtsecizelge;
            this.gridcontroltsecizelge.Name = "gridcontroltsecizelge";
            this.gridcontroltsecizelge.Size = new Size(0x2c4, 0x1bb);
            this.gridcontroltsecizelge.TabIndex = 8;
            BaseView[] views = new BaseView[] { this.gridviewtsecizelge };
            this.gridcontroltsecizelge.ViewCollection.AddRange(views);
            this.gridviewtsecizelge.Appearance.ColumnFilterButton.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.ColumnFilterButton.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.ColumnFilterButtonActive.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.ColumnFilterButtonActive.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.CustomizationFormHint.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.CustomizationFormHint.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.DetailTip.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.DetailTip.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.Empty.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.Empty.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.EvenRow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.EvenRow.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.FilterCloseButton.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.FilterCloseButton.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.FilterPanel.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.FilterPanel.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.FixedLine.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.FixedLine.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.FocusedCell.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.FocusedCell.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.FocusedRow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.FocusedRow.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.FooterPanel.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.FooterPanel.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.GroupButton.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.GroupButton.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.GroupFooter.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.GroupFooter.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.GroupPanel.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.GroupPanel.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.GroupRow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.GroupRow.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.HeaderPanel.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.HeaderPanel.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.HideSelectionRow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.HideSelectionRow.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.HorzLine.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.HorzLine.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.OddRow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.OddRow.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.Preview.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.Preview.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.Row.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.Row.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.RowSeparator.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.RowSeparator.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.SelectedRow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.SelectedRow.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.TopNewRow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.TopNewRow.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.VertLine.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.VertLine.Options.UseFont = true;
            this.gridviewtsecizelge.Appearance.ViewCaption.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridviewtsecizelge.Appearance.ViewCaption.Options.UseFont = true;
            GridColumn[] columns = new GridColumn[] { this.gridColumn1, this.gridColumn2, this.gridColumn3, this.gridColumn4, this.gridColumn5 };
            this.gridviewtsecizelge.Columns.AddRange(columns);
            this.gridviewtsecizelge.GridControl = this.gridcontroltsecizelge;
            this.gridviewtsecizelge.Name = "gridviewtsecizelge";
            this.gridviewtsecizelge.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.gridviewtsecizelge.OptionsSelection.EnableAppearanceFocusedRow = false;
            this.gridviewtsecizelge.OptionsView.ShowGroupPanel = false;
            this.gridviewtsecizelge.OptionsView.ShowIndicator = false;
            this.gridColumn1.AppearanceCell.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridColumn1.AppearanceCell.Options.UseFont = true;
            this.gridColumn1.AppearanceCell.Options.UseTextOptions = true;
            this.gridColumn1.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn1.AppearanceHeader.Font = new Font("Tahoma", 9f, FontStyle.Bold);
            this.gridColumn1.AppearanceHeader.ForeColor = Color.Maroon;
            this.gridColumn1.AppearanceHeader.Options.UseFont = true;
            this.gridColumn1.AppearanceHeader.Options.UseForeColor = true;
            this.gridColumn1.AppearanceHeader.Options.UseTextOptions = true;
            this.gridColumn1.AppearanceHeader.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn1.Caption = "Kişi Sayısı";
            this.gridColumn1.FieldName = "kisisay";
            this.gridColumn1.Name = "gridColumn1";
            this.gridColumn1.OptionsColumn.AllowEdit = false;
            this.gridColumn1.Visible = true;
            this.gridColumn1.VisibleIndex = 0;
            this.gridColumn1.Width = 0x5c;
            this.gridColumn2.AppearanceCell.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.gridColumn2.AppearanceCell.Options.UseFont = true;
            this.gridColumn2.AppearanceCell.Options.UseTextOptions = true;
            this.gridColumn2.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn2.AppearanceHeader.Font = new Font("Tahoma", 9f, FontStyle.Bold);
            this.gridColumn2.AppearanceHeader.ForeColor = Color.Maroon;
            this.gridColumn2.AppearanceHeader.Options.UseFont = true;
            this.gridColumn2.AppearanceHeader.Options.UseForeColor = true;
            this.gridColumn2.AppearanceHeader.Options.UseTextOptions = true;
            this.gridColumn2.AppearanceHeader.TextOptions.HAlignment = HorzAlignment.Center;
            this.gridColumn2.Caption = "Beyan Y\x00fck\x00fc";
            this.gridColumn2.FieldName = "beyanyuk";
            this.gridColumn2.Name = "gridColumn2";
            this.gridColumn2.OptionsColumn.AllowEdit = false;
            this.gridColumn2.Visible = true;
            this.gridColumn2.VisibleIndex = 1;
            this.gridColumn2.Width = 0x60;
            this.kabinalan.Location = new Point(0x219, 7);
            this.kabinalan.Name = "kabinalan";
            this.kabinalan.Properties.Appearance.BackColor = SystemColors.Control;
            this.kabinalan.Properties.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.kabinalan.Properties.Appearance.Options.UseBackColor = true;
            this.kabinalan.Properties.Appearance.Options.UseFont = true;
            this.kabinalan.Properties.Appearance.Options.UseTextOptions = true;
            this.kabinalan.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Center;
            this.kabinalan.Properties.BorderStyle = BorderStyles.NoBorder;
            this.kabinalan.Properties.ReadOnly = true;
            this.kabinalan.Size = new Size(50, 0x12);
            this.kabinalan.StyleController = this.layoutControl1;
            this.kabinalan.TabIndex = 6;
            this.kabinder.EnterMoveNextControl = true;
            this.kabinder.Location = new Point(0x13f, 7);
            this.kabinder.Name = "kabinder";
            this.kabinder.Properties.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.kabinder.Properties.Appearance.Options.UseFont = true;
            this.kabinder.Size = new Size(0x52, 20);
            this.kabinder.StyleController = this.layoutControl1;
            this.kabinder.TabIndex = 5;
            this.kabingen.EnterMoveNextControl = true;
            this.kabingen.Location = new Point(0x6d, 7);
            this.kabingen.Name = "kabingen";
            this.kabingen.Properties.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa2);
            this.kabingen.Properties.Appearance.Options.UseFont = true;
            this.kabingen.Size = new Size(70, 20);
            this.kabingen.StyleController = this.layoutControl1;
            this.kabingen.TabIndex = 4;
            this.layoutControlGroup1.CustomizationFormText = "layoutControlGroup1";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            BaseLayoutItem[] items = new BaseLayoutItem[] { this.labeltsekabingen, this.layoutControlItem5, this.layoutControlItem6, this.layoutControlItem1, this.layoutControlItem3, this.labeltsekabinder, this.layoutControlItem4, this.labeltsekabinalan, this.layoutControlItem7, this.layoutControlItem8, this.layoutControlItem2 };
            this.layoutControlGroup1.Items.AddRange(items);
            this.layoutControlGroup1.Location = new Point(0, 0);
            this.layoutControlGroup1.Name = "layoutControlGroup1";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(5, 5, 5, 5);
            this.layoutControlGroup1.Size = new Size(0x2d2, 0x229);
            this.layoutControlGroup1.TextVisible = false;
            this.labeltsekabingen.AppearanceItemCaption.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsekabingen.AppearanceItemCaption.Options.UseFont = true;
            this.labeltsekabingen.Control = this.kabingen;
            this.labeltsekabingen.CustomizationFormText = "Kabin Genişliği : ";
            this.labeltsekabingen.Location = new Point(0, 0);
            this.labeltsekabingen.Name = "labeltsekabingen";
            this.labeltsekabingen.Size = new Size(0xb0, 0x1a);
            this.labeltsekabingen.Text = "Kabin Genişliği : ";
            this.labeltsekabingen.TextSize = new Size(0x63, 14);
            this.layoutControlItem5.Control = this.gridcontroltsecizelge;
            this.layoutControlItem5.CustomizationFormText = "layoutControlItem5";
            this.layoutControlItem5.Location = new Point(0, 0x1a);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Size = new Size(0x2c8, 0x1c9);
            this.layoutControlItem5.Spacing = new DevExpress.XtraLayout.Utils.Padding(0, 0, 10, 0);
            this.layoutControlItem5.TextSize = new Size(0, 0);
            this.layoutControlItem5.TextVisible = false;
            this.layoutControlItem6.Control = this.labeltsemm;
            this.layoutControlItem6.CustomizationFormText = "layoutControlItem6";
            this.layoutControlItem6.Location = new Point(0x18e, 0);
            this.layoutControlItem6.MaxSize = new Size(0, 0x18);
            this.layoutControlItem6.MinSize = new Size(15, 0x18);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Size = new Size(30, 0x1a);
            this.layoutControlItem6.SizeConstraintsType = SizeConstraintsType.Custom;
            this.layoutControlItem6.TextSize = new Size(0, 0);
            this.layoutControlItem6.TextVisible = false;
            this.layoutControlItem1.Control = this.labeltsecizelge6;
            this.layoutControlItem1.Location = new Point(0, 0x1e3);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new Size(0x2c8, 0x12);
            this.layoutControlItem1.TextSize = new Size(0, 0);
            this.layoutControlItem1.TextVisible = false;
            this.layoutControlItem3.Control = this.labeltsecizelge8;
            this.layoutControlItem3.Location = new Point(0, 0x20d);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new Size(0x2c8, 0x12);
            this.layoutControlItem3.TextSize = new Size(0, 0);
            this.layoutControlItem3.TextVisible = false;
            this.labeltsekabinder.AppearanceItemCaption.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsekabinder.AppearanceItemCaption.Options.UseFont = true;
            this.labeltsekabinder.Control = this.kabinder;
            this.labeltsekabinder.CustomizationFormText = "Kabin Derinliği : ";
            this.labeltsekabinder.Location = new Point(210, 0);
            this.labeltsekabinder.Name = "labeltsekabinder";
            this.labeltsekabinder.Size = new Size(0xbc, 0x1a);
            this.labeltsekabinder.Text = "Kabin Derinliği : ";
            this.labeltsekabinder.TextSize = new Size(0x63, 14);
            this.layoutControlItem4.Control = this.labeltsemm2;
            this.layoutControlItem4.Location = new Point(0xb0, 0);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Size = new Size(0x22, 0x1a);
            this.layoutControlItem4.TextSize = new Size(0, 0);
            this.layoutControlItem4.TextVisible = false;
            this.labeltsekabinalan.AppearanceItemCaption.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa2);
            this.labeltsekabinalan.AppearanceItemCaption.Options.UseFont = true;
            this.labeltsekabinalan.Control = this.kabinalan;
            this.labeltsekabinalan.CustomizationFormText = "Kabin Alanı : ";
            this.labeltsekabinalan.Location = new Point(0x1ac, 0);
            this.labeltsekabinalan.Name = "labeltsekabinalan";
            this.labeltsekabinalan.Size = new Size(0x9c, 0x1a);
            this.labeltsekabinalan.Text = "Kabin Alanı : ";
            this.labeltsekabinalan.TextSize = new Size(0x63, 14);
            this.layoutControlItem7.Control = this.labeltsem2;
            this.layoutControlItem7.Location = new Point(0x248, 0);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Size = new Size(0x19, 0x1a);
            this.layoutControlItem7.TextSize = new Size(0, 0);
            this.layoutControlItem7.TextVisible = false;
            this.layoutControlItem8.Control = this.label1;
            this.layoutControlItem8.Location = new Point(0, 0x1f5);
            this.layoutControlItem8.Name = "layoutControlItem8";
            this.layoutControlItem8.Size = new Size(0x2c8, 0x18);
            this.layoutControlItem8.TextSize = new Size(0, 0);
            this.layoutControlItem8.TextVisible = false;
            this.layoutControlItem2.Control = this.simpleButton1;
            this.layoutControlItem2.Location = new Point(0x261, 0);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new Size(0x67, 0x1a);
            this.layoutControlItem2.TextSize = new Size(0, 0);
            this.layoutControlItem2.TextVisible = false;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x2d2, 0x229);
            base.Controls.Add(this.layoutControl1);
            this.MinimumSize = new Size(0x2e2, 0x215);
            base.Name = "tsestandart";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "TSE STANDARTLARI";
            base.Load += new EventHandler(this.tsestandart_Load);
            this.layoutControl1.EndInit();
            this.layoutControl1.ResumeLayout(false);
            this.gridcontroltsecizelge.EndInit();
            this.gridviewtsecizelge.EndInit();
            this.kabinalan.Properties.EndInit();
            this.kabinder.Properties.EndInit();
            this.kabingen.Properties.EndInit();
            this.layoutControlGroup1.EndInit();
            this.labeltsekabingen.EndInit();
            this.layoutControlItem5.EndInit();
            this.layoutControlItem6.EndInit();
            this.layoutControlItem1.EndInit();
            this.layoutControlItem3.EndInit();
            this.labeltsekabinder.EndInit();
            this.layoutControlItem4.EndInit();
            this.labeltsekabinalan.EndInit();
            this.layoutControlItem7.EndInit();
            this.layoutControlItem8.EndInit();
            this.layoutControlItem2.EndInit();
            base.ResumeLayout(false);
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                decimal num = new decimal();
                decimal num2 = new decimal();
                decimal num3 = new decimal();
                if ((this.kabingen.Text != "") && (this.kabinder.Text != ""))
                {
                    num3 = Convert.ToDecimal(this.kabingen.Text);
                    num2 = Convert.ToDecimal(this.kabinder.Text);
                    num = decimal.Round((num3 * num2) / 1000000M, 2);
                    this.kabinalan.Text = $"{num:#.00#}";
                }
                this.gridviewtsecizelge.FormatRules.Clear();
                GridFormatRule rule = new GridFormatRule();
                FormatConditionRuleExpression expression = new FormatConditionRuleExpression {
                    Appearance = { BackColor = Color.FromArgb(0x80, 0xff, 0x80) }
                };
                rule.ApplyToRow = true;
                string str = num.ToString().Replace(",", ".");
                string[] textArray1 = new string[] { "[cizelge8] <=", str, " And ", str, " <= [cizelge6]" };
                expression.Expression = string.Concat(textArray1);
                rule.Rule = expression;
                this.gridviewtsecizelge.FormatRules.Add(rule);
            }
            catch (Exception)
            {
            }
        }

        private void tsestandart_Load(object sender, EventArgs e)
        {
            try
            {
                decimal num = new decimal();
                decimal num2 = new decimal();
                decimal num3 = new decimal();
                num3 = Convert.ToDecimal(this.kabingenstr);
                num2 = Convert.ToDecimal(this.kabinderstr);
                num = decimal.Round((num3 * num2) / 1000000M, 2);
                this.kabinalan.Text = $"{num:#.00#}";
                this.gridcontroltsecizelge.DataSource = this.xx.dtta("select *  from cizelge", "");
                this.gridviewtsecizelge.FormatRules.Clear();
                GridFormatRule rule = new GridFormatRule();
                FormatConditionRuleExpression expression = new FormatConditionRuleExpression {
                    Appearance = { BackColor = Color.FromArgb(0x80, 0xff, 0x80) }
                };
                rule.ApplyToRow = true;
                string str = num.ToString().Replace(",", ".");
                string[] textArray1 = new string[] { "[cizelge8] <=", str, " And ", str, " <= [cizelge6]" };
                expression.Expression = string.Concat(textArray1);
                rule.Rule = expression;
                this.gridviewtsecizelge.FormatRules.Add(rule);
            }
            catch (Exception exception)
            {
                MessageBox.Show(exception.Message);
            }
            this.kabingen.Text = this.kabingenstr;
            this.kabinder.Text = this.kabinderstr;
        }
    }
}

