import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  ArcEntity,
  ToolName,
  Point2D,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Arc tool: three-point arc.
 * Click start, click point on arc, click end.
 * Computes center and radius from three points.
 */
export class ArcTool extends BaseTool {
  readonly name: ToolName = 'arc';
  readonly prompt = 'Specify start point of arc';

  private point1: Point2D | null = null;
  private point2: Point2D | null = null;
  private currentPoint: Point2D | null = null;
  private clickCount = 0;

  activate(): void {
    super.activate();
    this.point1 = null;
    this.point2 = null;
    this.currentPoint = null;
    this.clickCount = 0;
    this.setState('idle');
  }

  cancel(): void {
    this.point1 = null;
    this.point2 = null;
    this.currentPoint = null;
    this.clickCount = 0;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    const lastPt = this.clickCount === 1 ? this.point1 : this.clickCount === 2 ? this.point2 : undefined;
    const pt = this.applySnap(event, lastPt ?? undefined);

    this.clickCount++;

    if (this.clickCount === 1) {
      this.point1 = pt;
      this.setState('first_point');
    } else if (this.clickCount === 2) {
      this.point2 = pt;
      this.setState('preview');
    } else if (this.clickCount === 3) {
      this.createArc(this.point1!, this.point2!, pt);
      this.point1 = null;
      this.point2 = null;
      this.currentPoint = null;
      this.clickCount = 0;
      this.setState('idle');
    }
  }

  onMouseMove(event: CadMouseEvent): void {
    if (this.clickCount >= 1) {
      const lastPt = this.clickCount === 1 ? this.point1 : this.point2;
      this.currentPoint = this.applySnap(event, lastPt ?? undefined);
    }
  }

  onMouseUp(_event: CadMouseEvent): void {}

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.cancel();
    }
  }

  onNumericInput(_value: number): void {
    // Not used for three-point arc
  }

  getPreviewEntities(): CadEntity[] {
    if (this.clickCount < 1 || !this.currentPoint) return [];

    if (this.clickCount === 1 && this.point1) {
      // Show a line from point1 to cursor
      return [];
    }

    if (this.clickCount === 2 && this.point1 && this.point2) {
      const result = computeArcFromThreePoints(this.point1, this.point2, this.currentPoint);
      if (!result) return [];

      const defaults = this.getActiveLayerDefaults();
      const preview: ArcEntity = {
        id: 'preview-arc',
        type: 'arc',
        center: result.center,
        radius: result.radius,
        startAngle: result.startAngle,
        endAngle: result.endAngle,
        visible: true,
        locked: false,
        autoGenerated: false,
        ...defaults,
      };
      return [preview];
    }

    return [];
  }

  private createArc(p1: Point2D, p2: Point2D, p3: Point2D): void {
    const result = computeArcFromThreePoints(p1, p2, p3);
    if (!result) return;

    const defaults = this.getActiveLayerDefaults();
    const entity: ArcEntity = {
      id: v4(),
      type: 'arc',
      center: result.center,
      radius: result.radius,
      startAngle: result.startAngle,
      endAngle: result.endAngle,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };

    const cmd = new CreateEntityCommand(entity, this.entityModel);
    this.commandStack.execute(cmd);
  }
}

/**
 * Compute arc center, radius, startAngle, endAngle from three points.
 * Uses circumscribed circle formula.
 */
export function computeArcFromThreePoints(
  p1: Point2D,
  p2: Point2D,
  p3: Point2D
): { center: Point2D; radius: number; startAngle: number; endAngle: number } | null {
  const ax = p1.x, ay = p1.y;
  const bx = p2.x, by = p2.y;
  const cx = p3.x, cy = p3.y;

  const D = 2 * (ax * (by - cy) + bx * (cy - ay) + cx * (ay - by));
  if (Math.abs(D) < 1e-10) return null; // Collinear points

  const ux = ((ax * ax + ay * ay) * (by - cy) + (bx * bx + by * by) * (cy - ay) + (cx * cx + cy * cy) * (ay - by)) / D;
  const uy = ((ax * ax + ay * ay) * (cx - bx) + (bx * bx + by * by) * (ax - cx) + (cx * cx + cy * cy) * (bx - ax)) / D;

  const center: Point2D = { x: ux, y: uy };
  const radius = Math.sqrt((ax - ux) * (ax - ux) + (ay - uy) * (ay - uy));

  // Compute angles
  const angle1 = Math.atan2(ay - uy, ax - ux);
  const angle2 = Math.atan2(by - uy, bx - ux);
  const angle3 = Math.atan2(cy - uy, cx - ux);

  // Determine arc direction: ensure p2 is between p1 and p3
  // Normalize angles to [0, 2π)
  const norm = (a: number) => ((a % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
  const a1 = norm(angle1);
  const a2 = norm(angle2);
  const a3 = norm(angle3);

  // Check if going CCW from a1 to a3 passes through a2
  const ccwSpan = norm(a3 - a1);
  const ccwToMid = norm(a2 - a1);

  if (ccwToMid <= ccwSpan) {
    // CCW from p1 to p3 passes through p2
    return { center, radius, startAngle: a1, endAngle: a3 };
  } else {
    // CW: swap start and end
    return { center, radius, startAngle: a3, endAngle: a1 };
  }
}
