import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  CircleEntity,
  ToolName,
  Point2D,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Circle tool: center + radius → CircleEntity.
 * First click = center, second click or numeric input = radius.
 */
export class CircleTool extends BaseTool {
  readonly name: ToolName = 'circle';
  readonly prompt = 'Specify center point';

  private center: Point2D | null = null;
  private currentPoint: Point2D | null = null;

  activate(): void {
    super.activate();
    this.center = null;
    this.currentPoint = null;
    this.setState('idle');
  }

  cancel(): void {
    this.center = null;
    this.currentPoint = null;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    const pt = this.applySnap(event, this.center ?? undefined);

    if (this.state === 'idle') {
      this.center = pt;
      this.currentPoint = pt;
      this.setState('first_point');
    } else if (this.state === 'first_point' || this.state === 'preview') {
      const radius = distance(this.center!, pt);
      if (radius > 0) {
        this.createCircle(this.center!, radius);
      }
      this.center = null;
      this.currentPoint = null;
      this.setState('idle');
    }
  }

  onMouseMove(event: CadMouseEvent): void {
    if (this.state === 'first_point' || this.state === 'preview') {
      this.currentPoint = this.applySnap(event, this.center ?? undefined);
      this.setState('preview');
    }
  }

  onMouseUp(_event: CadMouseEvent): void {}

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.cancel();
    }
  }

  onNumericInput(value: number): void {
    if (!this.center || value <= 0) return;
    this.createCircle(this.center, value);
    this.center = null;
    this.currentPoint = null;
    this.setState('idle');
  }

  getPreviewEntities(): CadEntity[] {
    if (!this.center || !this.currentPoint) return [];

    const radius = distance(this.center, this.currentPoint);
    if (radius <= 0) return [];

    const defaults = this.getActiveLayerDefaults();
    const preview: CircleEntity = {
      id: 'preview-circle',
      type: 'circle',
      center: this.center,
      radius,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };
    return [preview];
  }

  private createCircle(center: Point2D, radius: number): void {
    const defaults = this.getActiveLayerDefaults();
    const entity: CircleEntity = {
      id: v4(),
      type: 'circle',
      center: { ...center },
      radius,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };

    const cmd = new CreateEntityCommand(entity, this.entityModel);
    this.commandStack.execute(cmd);
  }
}

function distance(a: Point2D, b: Point2D): number {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}
