import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  ToolName,
  Point2D,
  Command,
  LineEntity,
  PolylineEntity,
  CircleEntity,
  ArcEntity,
  DimensionEntity,
  TextEntity,
  BlockReferenceEntity,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Copy tool: base point + destination → duplicate selected entities at destination.
 */
export class CopyTool extends BaseTool {
  readonly name: ToolName = 'copy';
  readonly prompt = 'Specify base point';

  private basePoint: Point2D | null = null;
  private currentPoint: Point2D | null = null;

  activate(): void {
    super.activate();
    this.basePoint = null;
    this.currentPoint = null;
    this.setState('idle');
  }

  cancel(): void {
    this.basePoint = null;
    this.currentPoint = null;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    const pt = this.applySnap(event, this.basePoint ?? undefined);

    if (this.state === 'idle') {
      if (this.selectionManager.getSelectionCount() === 0) return;
      this.basePoint = pt;
      this.setState('first_point');
    } else if (this.state === 'first_point' || this.state === 'preview') {
      const dx = pt.x - this.basePoint!.x;
      const dy = pt.y - this.basePoint!.y;
      this.copySelected(dx, dy);
      this.basePoint = null;
      this.currentPoint = null;
      this.setState('idle');
    }
  }

  onMouseMove(event: CadMouseEvent): void {
    if (this.state === 'first_point' || this.state === 'preview') {
      this.currentPoint = this.applySnap(event, this.basePoint ?? undefined);
      this.setState('preview');
    }
  }

  onMouseUp(_event: CadMouseEvent): void {}

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') this.cancel();
  }

  onNumericInput(_value: number): void {}

  getPreviewEntities(): CadEntity[] {
    return [];
  }

  private copySelected(dx: number, dy: number): void {
    const entities = this.selectionManager.getSelectedEntities();
    if (entities.length === 0) return;

    this.commandStack.beginGroup('Copy entities');
    for (const entity of entities) {
      const copy = this.cloneAndTranslate(entity, dx, dy);
      if (copy) {
        const cmd = new CreateEntityCommand(copy, this.entityModel);
        this.commandStack.execute(cmd);
      }
    }
    this.commandStack.endGroup();
  }

  private cloneAndTranslate(entity: CadEntity, dx: number, dy: number): CadEntity | null {
    const newId = v4();
    const base = {
      ...entity,
      id: newId,
      autoGenerated: false,
      sourceParam: undefined,
    };

    switch (entity.type) {
      case 'line': {
        const l = entity as LineEntity;
        return { ...base, start: { x: l.start.x + dx, y: l.start.y + dy }, end: { x: l.end.x + dx, y: l.end.y + dy } } as LineEntity;
      }
      case 'polyline': {
        const p = entity as PolylineEntity;
        return { ...base, vertices: p.vertices.map((v) => ({ x: v.x + dx, y: v.y + dy })) } as PolylineEntity;
      }
      case 'circle': {
        const c = entity as CircleEntity;
        return { ...base, center: { x: c.center.x + dx, y: c.center.y + dy } } as CircleEntity;
      }
      case 'arc': {
        const a = entity as ArcEntity;
        return { ...base, center: { x: a.center.x + dx, y: a.center.y + dy } } as ArcEntity;
      }
      case 'dimension': {
        const d = entity as DimensionEntity;
        return {
          ...base,
          defPoint1: { x: d.defPoint1.x + dx, y: d.defPoint1.y + dy },
          defPoint2: { x: d.defPoint2.x + dx, y: d.defPoint2.y + dy },
          dimLinePoint: { x: d.dimLinePoint.x + dx, y: d.dimLinePoint.y + dy },
        } as DimensionEntity;
      }
      case 'text': {
        const t = entity as TextEntity;
        return { ...base, position: { x: t.position.x + dx, y: t.position.y + dy } } as TextEntity;
      }
      case 'block_reference': {
        const b = entity as BlockReferenceEntity;
        return { ...base, insertionPoint: { x: b.insertionPoint.x + dx, y: b.insertionPoint.y + dy } } as BlockReferenceEntity;
      }
      default:
        return null;
    }
  }
}
