import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  DimensionEntity,
  ToolName,
  Point2D,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Dimension tool: two definition points + dimension line position → DimensionEntity.
 * Auto-computes measurementValue from definition points.
 */
export class DimensionTool extends BaseTool {
  readonly name: ToolName = 'dimension';
  readonly prompt = 'Specify first definition point';

  private defPoint1: Point2D | null = null;
  private defPoint2: Point2D | null = null;
  private currentPoint: Point2D | null = null;
  private clickCount = 0;

  activate(): void {
    super.activate();
    this.defPoint1 = null;
    this.defPoint2 = null;
    this.currentPoint = null;
    this.clickCount = 0;
    this.setState('idle');
  }

  cancel(): void {
    this.defPoint1 = null;
    this.defPoint2 = null;
    this.currentPoint = null;
    this.clickCount = 0;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    const lastPt = this.clickCount === 1 ? this.defPoint1 : this.clickCount === 2 ? this.defPoint2 : undefined;
    const pt = this.applySnap(event, lastPt ?? undefined);

    this.clickCount++;

    if (this.clickCount === 1) {
      this.defPoint1 = pt;
      this.setState('first_point');
    } else if (this.clickCount === 2) {
      this.defPoint2 = pt;
      this.setState('preview');
    } else if (this.clickCount === 3) {
      this.createDimension(this.defPoint1!, this.defPoint2!, pt);
      this.defPoint1 = null;
      this.defPoint2 = null;
      this.currentPoint = null;
      this.clickCount = 0;
      this.setState('idle');
    }
  }

  onMouseMove(event: CadMouseEvent): void {
    if (this.clickCount >= 1) {
      const lastPt = this.clickCount === 1 ? this.defPoint1 : this.defPoint2;
      this.currentPoint = this.applySnap(event, lastPt ?? undefined);
    }
  }

  onMouseUp(_event: CadMouseEvent): void {}

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.cancel();
    }
  }

  onNumericInput(_value: number): void {
    // Not used for dimension tool
  }

  getPreviewEntities(): CadEntity[] {
    if (this.clickCount < 2 || !this.defPoint1 || !this.defPoint2 || !this.currentPoint) return [];

    const measurement = computeDistance(this.defPoint1, this.defPoint2);
    const defaults = this.getActiveLayerDefaults();

    const preview: DimensionEntity = {
      id: 'preview-dimension',
      type: 'dimension',
      dimensionType: 'linear',
      defPoint1: this.defPoint1,
      defPoint2: this.defPoint2,
      dimLinePoint: this.currentPoint,
      measurementValue: measurement,
      textHeight: 2.5,
      arrowSize: 2.5,
      extensionLineOffset: 1.5,
      decimalPrecision: 0,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };
    return [preview];
  }

  private createDimension(dp1: Point2D, dp2: Point2D, dimLinePt: Point2D): void {
    const measurement = computeDistance(dp1, dp2);
    const layer = this.entityModel.getLayer('Dimensions') ?? this.entityModel.getActiveLayer();

    const entity: DimensionEntity = {
      id: v4(),
      type: 'dimension',
      dimensionType: 'linear',
      defPoint1: { ...dp1 },
      defPoint2: { ...dp2 },
      dimLinePoint: { ...dimLinePt },
      measurementValue: measurement,
      textHeight: 2.5,
      arrowSize: 2.5,
      extensionLineOffset: 1.5,
      decimalPrecision: 0,
      visible: true,
      locked: false,
      autoGenerated: false,
      layerName: layer.name,
      color: layer.color,
      lineType: layer.lineType,
      lineWeight: layer.lineWeight,
    };

    const cmd = new CreateEntityCommand(entity, this.entityModel);
    this.commandStack.execute(cmd);
  }
}

function computeDistance(a: Point2D, b: Point2D): number {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}
