import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  LineEntity,
  ToolName,
  Point2D,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Line drawing tool: two clicks to create a LineEntity.
 * Preview: rubber-band line from start to cursor.
 * Numeric input = distance along current direction.
 */
export class LineTool extends BaseTool {
  readonly name: ToolName = 'line';
  readonly prompt = 'Specify first point';

  private startPoint: Point2D | null = null;
  private currentPoint: Point2D | null = null;

  activate(): void {
    super.activate();
    this.startPoint = null;
    this.currentPoint = null;
    this.setState('idle');
  }

  cancel(): void {
    this.startPoint = null;
    this.currentPoint = null;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    const pt = this.applySnap(event, this.startPoint ?? undefined);

    if (this.state === 'idle') {
      this.startPoint = pt;
      this.currentPoint = pt;
      this.setState('first_point');
    } else if (this.state === 'first_point' || this.state === 'preview') {
      this.createLine(this.startPoint!, pt);
      // Reset for next line
      this.startPoint = null;
      this.currentPoint = null;
      this.setState('idle');
    }
  }

  onMouseMove(event: CadMouseEvent): void {
    if (this.state === 'first_point' || this.state === 'preview') {
      this.currentPoint = this.applySnap(event, this.startPoint ?? undefined);
      this.setState('preview');
    }
  }

  onMouseUp(_event: CadMouseEvent): void {
    // Not used for line tool
  }

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.cancel();
    }
  }

  onNumericInput(value: number): void {
    if (!this.startPoint || !this.currentPoint) return;

    // Use numeric input as distance along current direction
    const dx = this.currentPoint.x - this.startPoint.x;
    const dy = this.currentPoint.y - this.startPoint.y;
    const len = Math.sqrt(dx * dx + dy * dy);

    if (len === 0) return;

    const endPoint: Point2D = {
      x: this.startPoint.x + (dx / len) * value,
      y: this.startPoint.y + (dy / len) * value,
    };

    this.createLine(this.startPoint, endPoint);
    this.startPoint = null;
    this.currentPoint = null;
    this.setState('idle');
  }

  getPreviewEntities(): CadEntity[] {
    if (!this.startPoint || !this.currentPoint) return [];
    if (this.state !== 'preview' && this.state !== 'first_point') return [];

    const defaults = this.getActiveLayerDefaults();
    const preview: LineEntity = {
      id: 'preview-line',
      type: 'line',
      start: this.startPoint,
      end: this.currentPoint,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };
    return [preview];
  }

  private createLine(start: Point2D, end: Point2D): void {
    const defaults = this.getActiveLayerDefaults();
    const entity: LineEntity = {
      id: v4(),
      type: 'line',
      start: { ...start },
      end: { ...end },
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };

    const cmd = new CreateEntityCommand(entity, this.entityModel);
    this.commandStack.execute(cmd);
  }
}
