import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  ToolName,
  Point2D,
  LineEntity,
  PolylineEntity,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Offset tool: distance + click entity → parallel copy at offset distance.
 * Works on lines and polylines.
 */
export class OffsetTool extends BaseTool {
  readonly name: ToolName = 'offset';
  readonly prompt = 'Specify offset distance';

  private offsetDistance: number | null = null;
  private selectedEntity: CadEntity | null = null;

  activate(): void {
    super.activate();
    this.offsetDistance = null;
    this.selectedEntity = null;
    this.setState('idle');
  }

  cancel(): void {
    this.offsetDistance = null;
    this.selectedEntity = null;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    if (this.offsetDistance === null) {
      // Need distance first — wait for numeric input
      return;
    }

    const worldPt: Point2D = { x: event.worldX, y: event.worldY };
    const tolerance = 5 / this.viewport.zoom;

    if (!this.selectedEntity) {
      // Select entity to offset
      const hit = this.entityModel.hitTest(worldPt, tolerance);
      if (hit && (hit.type === 'line' || hit.type === 'polyline')) {
        this.selectedEntity = hit;
        this.setState('preview');
      }
    } else {
      // Determine offset side based on click position
      const side = this.determineSide(this.selectedEntity, worldPt);
      this.createOffset(this.selectedEntity, this.offsetDistance, side);
      this.selectedEntity = null;
      this.setState('first_point');
    }
  }

  onMouseMove(_event: CadMouseEvent): void {}

  onMouseUp(_event: CadMouseEvent): void {}

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') this.cancel();
  }

  onNumericInput(value: number): void {
    if (value > 0) {
      this.offsetDistance = value;
      this.setState('first_point');
    }
  }

  getPreviewEntities(): CadEntity[] {
    return [];
  }

  private determineSide(entity: CadEntity, clickPoint: Point2D): number {
    if (entity.type === 'line') {
      const line = entity as LineEntity;
      const cross = (line.end.x - line.start.x) * (clickPoint.y - line.start.y) -
                    (line.end.y - line.start.y) * (clickPoint.x - line.start.x);
      return cross >= 0 ? 1 : -1;
    }
    // For polylines, use first segment
    if (entity.type === 'polyline') {
      const poly = entity as PolylineEntity;
      if (poly.vertices.length < 2) return 1;
      const cross = (poly.vertices[1].x - poly.vertices[0].x) * (clickPoint.y - poly.vertices[0].y) -
                    (poly.vertices[1].y - poly.vertices[0].y) * (clickPoint.x - poly.vertices[0].x);
      return cross >= 0 ? 1 : -1;
    }
    return 1;
  }

  private createOffset(entity: CadEntity, dist: number, side: number): void {
    if (entity.type === 'line') {
      this.offsetLine(entity as LineEntity, dist, side);
    } else if (entity.type === 'polyline') {
      this.offsetPolyline(entity as PolylineEntity, dist, side);
    }
  }

  private offsetLine(line: LineEntity, dist: number, side: number): void {
    const dx = line.end.x - line.start.x;
    const dy = line.end.y - line.start.y;
    const len = Math.sqrt(dx * dx + dy * dy);
    if (len === 0) return;

    // Normal vector (perpendicular)
    const nx = (-dy / len) * dist * side;
    const ny = (dx / len) * dist * side;

    const defaults = this.getActiveLayerDefaults();
    const newLine: LineEntity = {
      id: v4(),
      type: 'line',
      start: { x: line.start.x + nx, y: line.start.y + ny },
      end: { x: line.end.x + nx, y: line.end.y + ny },
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };

    const cmd = new CreateEntityCommand(newLine, this.entityModel);
    this.commandStack.execute(cmd);
  }

  private offsetPolyline(poly: PolylineEntity, dist: number, side: number): void {
    if (poly.vertices.length < 2) return;

    const offsetVerts: Point2D[] = [];

    for (let i = 0; i < poly.vertices.length; i++) {
      const prev = poly.vertices[(i - 1 + poly.vertices.length) % poly.vertices.length];
      const curr = poly.vertices[i];
      const next = poly.vertices[(i + 1) % poly.vertices.length];

      if (!poly.closed && i === 0) {
        // First vertex of open polyline
        const dx = next.x - curr.x;
        const dy = next.y - curr.y;
        const len = Math.sqrt(dx * dx + dy * dy);
        if (len === 0) { offsetVerts.push({ ...curr }); continue; }
        offsetVerts.push({
          x: curr.x + (-dy / len) * dist * side,
          y: curr.y + (dx / len) * dist * side,
        });
      } else if (!poly.closed && i === poly.vertices.length - 1) {
        // Last vertex of open polyline
        const dx = curr.x - prev.x;
        const dy = curr.y - prev.y;
        const len = Math.sqrt(dx * dx + dy * dy);
        if (len === 0) { offsetVerts.push({ ...curr }); continue; }
        offsetVerts.push({
          x: curr.x + (-dy / len) * dist * side,
          y: curr.y + (dx / len) * dist * side,
        });
      } else {
        // Interior vertex or closed polyline vertex — bisector offset
        const dx1 = curr.x - prev.x;
        const dy1 = curr.y - prev.y;
        const dx2 = next.x - curr.x;
        const dy2 = next.y - curr.y;
        const len1 = Math.sqrt(dx1 * dx1 + dy1 * dy1);
        const len2 = Math.sqrt(dx2 * dx2 + dy2 * dy2);

        if (len1 === 0 || len2 === 0) { offsetVerts.push({ ...curr }); continue; }

        const n1x = -dy1 / len1;
        const n1y = dx1 / len1;
        const n2x = -dy2 / len2;
        const n2y = dx2 / len2;

        const bisX = (n1x + n2x) / 2;
        const bisY = (n1y + n2y) / 2;
        const bisLen = Math.sqrt(bisX * bisX + bisY * bisY);

        if (bisLen === 0) { offsetVerts.push({ ...curr }); continue; }

        // Scale bisector to maintain offset distance
        const dot = n1x * bisX / bisLen + n1y * bisY / bisLen;
        const scale = dot !== 0 ? dist / dot : dist;

        offsetVerts.push({
          x: curr.x + (bisX / bisLen) * scale * side,
          y: curr.y + (bisY / bisLen) * scale * side,
        });
      }
    }

    const defaults = this.getActiveLayerDefaults();
    const newPoly: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: offsetVerts,
      closed: poly.closed,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };

    const cmd = new CreateEntityCommand(newPoly, this.entityModel);
    this.commandStack.execute(cmd);
  }
}
