import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  PolylineEntity,
  ToolName,
  Point2D,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Polyline tool: accumulate vertices with clicks.
 * Enter or right-click to finish → PolylineEntity.
 */
export class PolylineTool extends BaseTool {
  readonly name: ToolName = 'polyline';
  readonly prompt = 'Specify first point';

  private vertices: Point2D[] = [];
  private currentPoint: Point2D | null = null;

  activate(): void {
    super.activate();
    this.vertices = [];
    this.currentPoint = null;
    this.setState('idle');
  }

  cancel(): void {
    this.vertices = [];
    this.currentPoint = null;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    // Right-click to finish
    if (event.button === 2) {
      this.finishPolyline();
      return;
    }

    if (event.button !== 0) return;

    const lastPt = this.vertices.length > 0 ? this.vertices[this.vertices.length - 1] : undefined;
    const pt = this.applySnap(event, lastPt);

    this.vertices.push(pt);
    this.currentPoint = pt;

    if (this.vertices.length === 1) {
      this.setState('first_point');
    } else {
      this.setState('preview');
    }
  }

  onMouseMove(event: CadMouseEvent): void {
    if (this.vertices.length === 0) return;
    const lastPt = this.vertices[this.vertices.length - 1];
    this.currentPoint = this.applySnap(event, lastPt);
  }

  onMouseUp(_event: CadMouseEvent): void {
    // Not used
  }

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.finishPolyline();
    } else if (event.key === 'Escape') {
      this.cancel();
    }
  }

  onNumericInput(value: number): void {
    if (this.vertices.length === 0 || !this.currentPoint) return;

    const lastPt = this.vertices[this.vertices.length - 1];
    const dx = this.currentPoint.x - lastPt.x;
    const dy = this.currentPoint.y - lastPt.y;
    const len = Math.sqrt(dx * dx + dy * dy);

    if (len === 0) return;

    const newPt: Point2D = {
      x: lastPt.x + (dx / len) * value,
      y: lastPt.y + (dy / len) * value,
    };

    this.vertices.push(newPt);
    this.currentPoint = newPt;
  }

  getPreviewEntities(): CadEntity[] {
    if (this.vertices.length === 0) return [];

    const defaults = this.getActiveLayerDefaults();
    const previewVerts = [...this.vertices];
    if (this.currentPoint && this.vertices.length > 0) {
      previewVerts.push(this.currentPoint);
    }

    const preview: PolylineEntity = {
      id: 'preview-polyline',
      type: 'polyline',
      vertices: previewVerts,
      closed: false,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };
    return [preview];
  }

  private finishPolyline(): void {
    if (this.vertices.length < 2) {
      this.cancel();
      return;
    }

    const defaults = this.getActiveLayerDefaults();
    const entity: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: this.vertices.map((v) => ({ ...v })),
      closed: false,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };

    const cmd = new CreateEntityCommand(entity, this.entityModel);
    this.commandStack.execute(cmd);

    this.vertices = [];
    this.currentPoint = null;
    this.setState('idle');
  }
}
