import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  PolylineEntity,
  ToolName,
  Point2D,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Rectangle tool: two corners → closed PolylineEntity with 4 vertices.
 */
export class RectangleTool extends BaseTool {
  readonly name: ToolName = 'rectangle';
  readonly prompt = 'Specify first corner';

  private firstCorner: Point2D | null = null;
  private currentPoint: Point2D | null = null;

  activate(): void {
    super.activate();
    this.firstCorner = null;
    this.currentPoint = null;
    this.setState('idle');
  }

  cancel(): void {
    this.firstCorner = null;
    this.currentPoint = null;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    const pt = this.applySnap(event, this.firstCorner ?? undefined);

    if (this.state === 'idle') {
      this.firstCorner = pt;
      this.currentPoint = pt;
      this.setState('first_point');
    } else if (this.state === 'first_point' || this.state === 'preview') {
      this.createRectangle(this.firstCorner!, pt);
      this.firstCorner = null;
      this.currentPoint = null;
      this.setState('idle');
    }
  }

  onMouseMove(event: CadMouseEvent): void {
    if (this.state === 'first_point' || this.state === 'preview') {
      this.currentPoint = this.applySnap(event, this.firstCorner ?? undefined);
      this.setState('preview');
    }
  }

  onMouseUp(_event: CadMouseEvent): void {}

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.cancel();
    }
  }

  onNumericInput(_value: number): void {
    // Could support width,height input — not required for MVP
  }

  getPreviewEntities(): CadEntity[] {
    if (!this.firstCorner || !this.currentPoint) return [];

    const verts = this.computeVertices(this.firstCorner, this.currentPoint);
    const defaults = this.getActiveLayerDefaults();

    const preview: PolylineEntity = {
      id: 'preview-rectangle',
      type: 'polyline',
      vertices: verts,
      closed: true,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };
    return [preview];
  }

  private createRectangle(corner1: Point2D, corner2: Point2D): void {
    const verts = this.computeVertices(corner1, corner2);
    const defaults = this.getActiveLayerDefaults();

    const entity: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: verts,
      closed: true,
      visible: true,
      locked: false,
      autoGenerated: false,
      ...defaults,
    };

    const cmd = new CreateEntityCommand(entity, this.entityModel);
    this.commandStack.execute(cmd);
  }

  private computeVertices(c1: Point2D, c2: Point2D): Point2D[] {
    return [
      { x: c1.x, y: c1.y },
      { x: c2.x, y: c1.y },
      { x: c2.x, y: c2.y },
      { x: c1.x, y: c2.y },
    ];
  }
}
