import { v4 } from 'uuid';
import type {
  CadEntity,
  CadMouseEvent,
  TextEntity,
  ToolName,
  Point2D,
} from '../core/types';
import { BaseTool, CreateEntityCommand } from './BaseTool';

/**
 * Text tool: click position → prompt for text → TextEntity.
 */
export class TextTool extends BaseTool {
  readonly name: ToolName = 'text';
  readonly prompt = 'Specify text insertion point';

  private insertionPoint: Point2D | null = null;
  private pendingText: string | null = null;

  activate(): void {
    super.activate();
    this.insertionPoint = null;
    this.pendingText = null;
    this.setState('idle');
  }

  cancel(): void {
    this.insertionPoint = null;
    this.pendingText = null;
    super.cancel();
  }

  onMouseDown(event: CadMouseEvent): void {
    if (event.button !== 0) return;

    const pt = this.applySnap(event);

    if (this.state === 'idle') {
      this.insertionPoint = pt;
      this.setState('first_point');
      // In a real UI, this would open an inline text editor.
      // For now, create with a default text that can be edited via property panel.
      this.createText(pt, 'Text');
      this.insertionPoint = null;
      this.setState('idle');
    }
  }

  onMouseMove(_event: CadMouseEvent): void {
    // No preview needed for text tool
  }

  onMouseUp(_event: CadMouseEvent): void {}

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.cancel();
    }
  }

  onNumericInput(_value: number): void {
    // Not used for text tool
  }

  /** Allow external code (e.g., React UI) to set text content before creation. */
  setTextContent(text: string): void {
    this.pendingText = text;
  }

  /** Create text at a specific point with given content (for programmatic use). */
  createTextAt(position: Point2D, content: string): void {
    this.createText(position, content);
  }

  getPreviewEntities(): CadEntity[] {
    return [];
  }

  private createText(position: Point2D, content: string): void {
    const layer = this.entityModel.getLayer('Text') ?? this.entityModel.getActiveLayer();

    const entity: TextEntity = {
      id: v4(),
      type: 'text',
      position: { ...position },
      content: this.pendingText ?? content,
      fontSize: 3,
      fontFamily: 'Arial',
      fontWeight: 'normal',
      fontStyle: 'normal',
      alignment: 'left',
      rotation: 0,
      visible: true,
      locked: false,
      autoGenerated: false,
      layerName: layer.name,
      color: layer.color,
      lineType: layer.lineType,
      lineWeight: layer.lineWeight,
    };

    const cmd = new CreateEntityCommand(entity, this.entityModel);
    this.commandStack.execute(cmd);
    this.pendingText = null;
  }
}
