// =============================================================================
// Core Geometry Types
// =============================================================================

export interface Point2D {
  x: number;
  y: number;
}

export interface BoundingBox {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

export interface Transform2D {
  translateX: number;
  translateY: number;
  rotation: number;    // radians
  scaleX: number;
  scaleY: number;
}

// =============================================================================
// Base Entity
// =============================================================================

export type EntityType =
  | 'line' | 'polyline' | 'circle' | 'arc'
  | 'dimension' | 'text' | 'hatch' | 'block_reference';

export type LineType = 'continuous' | 'dashed' | 'center' | 'hidden';

export interface CadEntity {
  id: string;                  // UUID
  type: EntityType;
  layerName: string;
  color: string;               // hex color, e.g. '#FF0000'
  lineType: LineType;
  lineWeight: number;          // mm
  visible: boolean;
  locked: boolean;
  // Auto-generation tracking
  autoGenerated: boolean;
  sourceParam?: string;        // Lift parameter name that controls this entity
}

// =============================================================================
// Geometry Entities
// =============================================================================

export interface LineEntity extends CadEntity {
  type: 'line';
  start: Point2D;
  end: Point2D;
}

export interface PolylineEntity extends CadEntity {
  type: 'polyline';
  vertices: Point2D[];
  closed: boolean;
}

export interface CircleEntity extends CadEntity {
  type: 'circle';
  center: Point2D;
  radius: number;
}

export interface ArcEntity extends CadEntity {
  type: 'arc';
  center: Point2D;
  radius: number;
  startAngle: number;   // radians
  endAngle: number;      // radians
}

// =============================================================================
// Annotation Entities
// =============================================================================

export type DimensionType = 'linear' | 'aligned' | 'angular' | 'radial';

export interface DimensionEntity extends CadEntity {
  type: 'dimension';
  dimensionType: DimensionType;
  defPoint1: Point2D;          // first definition point
  defPoint2: Point2D;          // second definition point
  dimLinePoint: Point2D;       // dimension line position
  measurementValue: number;    // computed measurement in mm or degrees
  textOverride?: string;       // optional manual text override
  textHeight: number;          // mm
  arrowSize: number;           // mm
  extensionLineOffset: number; // mm
  decimalPrecision: number;    // number of decimal places
  // For angular dimensions
  angleVertex?: Point2D;
  // For radial dimensions
  centerPoint?: Point2D;
}

export interface TextEntity extends CadEntity {
  type: 'text';
  position: Point2D;
  content: string;
  fontSize: number;            // mm
  fontFamily: string;
  fontWeight: 'normal' | 'bold';
  fontStyle: 'normal' | 'italic';
  alignment: 'left' | 'center' | 'right';
  rotation: number;            // radians
}

export type HatchPattern = 'ANSI31' | 'ANSI32' | 'INSUL' | 'SOLID';

export interface HatchEntity extends CadEntity {
  type: 'hatch';
  pattern: HatchPattern;
  patternScale: number;
  patternAngle: number;        // radians
  boundaryEntityIds: string[]; // IDs of entities forming the closed boundary
  boundaryPoints: Point2D[];   // computed boundary polygon
}

// =============================================================================
// Block System
// =============================================================================

export interface BlockDefinition {
  name: string;
  displayName: string;
  basePoint: Point2D;
  entities: CadEntity[];       // geometry that makes up the block
  attributeDefs: BlockAttributeDef[];
  parameterBindings: Record<string, string>; // paramName → liftParamName
}

export interface BlockAttributeDef {
  tag: string;                 // attribute tag name
  prompt: string;              // prompt text
  defaultValue: string;
  position: Point2D;           // relative to block base point
  textHeight: number;
  visible: boolean;
}

export interface BlockReferenceEntity extends CadEntity {
  type: 'block_reference';
  blockDefName: string;
  insertionPoint: Point2D;
  rotation: number;            // radians
  scaleX: number;
  scaleY: number;
  attributes: Record<string, string>; // tag → value
}

// =============================================================================
// Parametric Block Definition
// =============================================================================

export interface ParametricBlockDef {
  name: string;
  displayName: string;
  parameterBindings: Record<string, string>; // e.g., { width: 'KabinGenisligi' }
  generate(params: Record<string, number>): CadEntity[];
  attributeDefinitions: BlockAttributeDef[];
}

// =============================================================================
// Layer
// =============================================================================

export interface Layer {
  name: string;
  visible: boolean;
  locked: boolean;
  color: string;               // hex color
  lineType: LineType;
  lineWeight: number;          // mm
}

// Default elevator drawing layers
export const DEFAULT_LAYERS: Layer[] = [
  { name: '0',              visible: true, locked: false, color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.25 },
  { name: 'Shaft',          visible: true, locked: false, color: '#808080', lineType: 'continuous', lineWeight: 0.50 },
  { name: 'Cabin',          visible: true, locked: false, color: '#2563EB', lineType: 'continuous', lineWeight: 0.35 },
  { name: 'Rails',          visible: true, locked: false, color: '#DC2626', lineType: 'continuous', lineWeight: 0.25 },
  { name: 'Doors',          visible: true, locked: false, color: '#EA580C', lineType: 'continuous', lineWeight: 0.35 },
  { name: 'Counterweight',  visible: true, locked: false, color: '#4B5563', lineType: 'continuous', lineWeight: 0.25 },
  { name: 'Dimensions',     visible: true, locked: false, color: '#06B6D4', lineType: 'continuous', lineWeight: 0.18 },
  { name: 'Text',           visible: true, locked: false, color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.18 },
  { name: 'Hatch',          visible: true, locked: false, color: '#16A34A', lineType: 'continuous', lineWeight: 0.13 },
  { name: 'TitleBlock',     visible: true, locked: false, color: '#A855F7', lineType: 'continuous', lineWeight: 0.50 },
];

// =============================================================================
// Drawing State & Persistence
// =============================================================================

export interface DrawingState {
  entities: CadEntity[];
  layers: Layer[];
  blockDefinitions: BlockDefinition[];
  activeLayerName: string;
  viewport: ViewportStateJson;
  metadata: DrawingMetadata;
}

export interface ViewportStateJson {
  centerX: number;
  centerY: number;
  zoom: number;
}

export interface DrawingMetadata {
  drawingType: DrawingType;
  liftId: string;
  createdAt: string;           // ISO 8601
  updatedAt: string;           // ISO 8601
  version: number;
}

// The JSON format sent to/from the server
export interface DrawingJson {
  version: 1;
  state: DrawingState;
}

// =============================================================================
// Lift Parameters (Client-Side Mirror)
// =============================================================================

// Mirrors the server Lift entity fields relevant to drawing generation
export interface LiftParams {
  id: string;
  asansorTipi: 'EA' | 'HA';
  tahrikKodu: 'DA' | 'MDDUZ' | 'MDCAP' | 'YA' | 'SD' | 'RAMD';
  yonKodu: 'SOL' | 'SAG' | 'ARKA';
  kuyuGenisligi: number;       // mm
  kuyuDerinligi: number;       // mm
  kuyuDibi: number;            // mm
  kuyuKafa: number;            // mm
  kabinGenisligi: number;      // mm
  kabinDerinligi: number;      // mm
  kabinYuksekligi: number;     // mm
  kapiGenisligi: number;       // mm
  kapiTipi: string;
  beyanYuk: number;            // kg
  beyanKisi: number;
  durakSayisi: number;
  ilkDurakNo: number;
  katYuksekligi: number;       // mm default floor height
  floors: FloorParam[];
  kabinRayStr: string;
  agrRayStr: string;
  panoramik: boolean;
  // Catalog references for block resolution
  cabinRailSpec?: RailSpec;
  counterweightRailSpec?: RailSpec;
  // Extended ASNCAD params from myData.cs
  kabinYEksen: number;         // mm - cabin Y axis offset from front wall
  kabinRayUcu: number;         // mm - rail tip clearance
  kabinRayFark: number;        // mm - rail difference (100 for DA, 250 for MDDUZ)
  kizakKalin: number;          // mm - guide shoe thickness
  krx: number;                 // mm - cabin rail X dimension (from rail string)
  kry: number;                 // mm - cabin rail Y dimension
  krz: number;                 // mm - cabin rail Z dimension
  arx: number;                 // mm - counterweight rail X dimension
  ary: number;                 // mm - counterweight rail Y dimension
  arz: number;                 // mm - counterweight rail Z dimension
  agrGen: number;              // mm - counterweight width
  agrDuv: number;              // mm - counterweight wall clearance
  agrU: number;                // mm - counterweight U clearance
  agrUz: number;               // mm - counterweight depth
  agrGir: number;              // mm - counterweight entrance (0 or 60 for barit)
  agrKabin: number;            // mm - counterweight-cabin clearance
  tahrikKas: number;           // mm - traction sheave diameter
  sapKas: number;              // mm - deflection sheave diameter
  mdTahrikKas: number;         // mm - MRL traction sheave
  mdSapKas: number;            // mm - MRL deflection sheave
  regYer: string;              // regulator position
  kabinTamponu: string;        // cabin buffer type
  agrTamponu: string;          // counterweight buffer type
  dengeZinciri: boolean;       // balance chain
  iskeleVar: boolean;          // scaffold exists
  mentese: string;             // hinge type
  kapiH: number;               // mm - door height
  esikKalin: number;           // mm - sill thickness
  duvarKal: number;            // mm - wall thickness (default 200)
  seyirMesafesi: number;       // mm - travel distance
  mdTabTavan: number;          // mm - machine room ceiling height
  // HAMD (hydraulic) params
  hamdGen: number;             // mm - hydraulic unit width
  hamdDer: number;             // mm - hydraulic unit depth
  makYon: 'SOL' | 'SAG';      // machine direction for HA
  // Firma bilgileri
  firmaAd: string;
  firmaAdres: string;
  firmaTel: string;
  firmaFax: string;
  firmaMail: string;
  firmaYetkili: string;
  firmaMarka: string;
  mmAd: string;                // mechanical engineer name
  mmOda: string;               // mechanical engineer chamber no
  mmBel: string;               // mechanical engineer certificate
  mmSmm: string;               // mechanical engineer SMM
  emAd: string;                // electrical engineer name
  emOda: string;
  emBel: string;
  emSmm: string;
}

export interface FloorParam {
  katNo: number;
  katRumuz: string;
  katYuksekligi: number;       // mm
  mimariKot: string;
}

export interface RailSpec {
  modelName: string;
  width: number;
  height: number;
  weight: number;
}

// =============================================================================
// Title Block
// =============================================================================

export interface TitleBlockData {
  companyName: string;
  companyAddress: string;
  companyPhone: string;
  projectName: string;
  drawingTitle: string;
  drawingNumber: string;
  scale: string;
  date: string;
  revision: string;
  mechanicalEngineerName: string;
  mechanicalEngineerSMM: string;
  electricalEngineerName: string;
  electricalEngineerSMM: string;
}

// =============================================================================
// Event Types
// =============================================================================

export type CadEvent =
  | 'selectionChanged'
  | 'entityAdded'
  | 'entityRemoved'
  | 'entityModified'
  | 'layerChanged'
  | 'toolChanged'
  | 'viewportChanged'
  | 'commandExecuted'
  | 'undoRedoChanged'
  | 'parameterChanged';

export type CadEventHandler = (data: any) => void;

export interface CadMouseEvent {
  screenX: number;
  screenY: number;
  worldX: number;
  worldY: number;
  button: number;
  shiftKey: boolean;
  ctrlKey: boolean;
}

// =============================================================================
// Snap Types
// =============================================================================

export type SnapMode = 'endpoint' | 'midpoint' | 'center' | 'intersection' | 'perpendicular' | 'nearest' | 'grid';

export interface SnapResult {
  point: Point2D;
  mode: SnapMode;
  entityId?: string;
}

// =============================================================================
// Tool Types
// =============================================================================

export type ToolName =
  | 'select' | 'line' | 'polyline' | 'rectangle'
  | 'circle' | 'arc' | 'dimension' | 'text'
  | 'move' | 'copy' | 'rotate' | 'scale'
  | 'mirror' | 'offset';

export type ToolState = 'idle' | 'first_point' | 'preview' | 'complete';

// =============================================================================
// Drawing & Export Types
// =============================================================================

export type DrawingType =
  | 'cross-section'
  | 'longitudinal'
  | 'machine-room'
  | 'cabin-plan'
  | 'pit-detail'
  | 'overhead-detail';

export type PdfScale = '1:50' | '1:100' | '1:200';

// =============================================================================
// 3D Viewer Types
// =============================================================================

export type ComponentCategory = 'shaft' | 'cabin' | 'rails' | 'counterweight' | 'machine' | 'doors' | 'buffers';

// =============================================================================
// Selection Types
// =============================================================================

export interface GripPoint {
  point: Point2D;
  entityId: string;
  gripType: string;
}

// =============================================================================
// Command Interface
// =============================================================================

export interface Command {
  readonly description: string;
  execute(): void;
  undo(): void;
}

// =============================================================================
// DXF Mapping Constants
// =============================================================================

// Maps hex colors to AutoCAD Color Index (ACI) numbers
export const COLOR_TO_ACI: Record<string, number> = {
  '#FF0000': 1,   // Red
  '#FFFF00': 2,   // Yellow
  '#00FF00': 3,   // Green
  '#00FFFF': 4,   // Cyan
  '#0000FF': 5,   // Blue
  '#FF00FF': 6,   // Magenta
  '#FFFFFF': 7,   // White
  '#808080': 8,   // Gray
  '#C0C0C0': 9,   // Light gray
  // Extended mappings for default layer colors
  '#2563EB': 5,   // Cabin → Blue
  '#DC2626': 1,   // Rails → Red
  '#EA580C': 30,  // Doors → Orange
  '#4B5563': 8,   // Counterweight → Gray
  '#06B6D4': 4,   // Dimensions → Cyan
  '#16A34A': 3,   // Hatch → Green
  '#A855F7': 6,   // TitleBlock → Magenta
};

// Maps LineType to DXF line type names
export const LINETYPE_TO_DXF: Record<LineType, string> = {
  'continuous': 'CONTINUOUS',
  'dashed': 'DASHED',
  'center': 'CENTER',
  'hidden': 'HIDDEN',
};
