import type { CadEntity, LiftParams, DrawingType } from '../core/types';
import type { EntityModel } from '../core/EntityModel';
import type { BlockLibrary } from '../blocks/BlockLibrary';
import { CrossSectionGenerator } from './CrossSectionGenerator';
import { LongitudinalGenerator } from './LongitudinalGenerator';
import { MachineRoomGenerator } from './MachineRoomGenerator';
import { CabinPlanGenerator } from './CabinPlanGenerator';
import { PitDetailGenerator } from './PitDetailGenerator';
import { OverheadDetailGenerator } from './OverheadDetailGenerator';

export interface GenerationResult {
  entities: CadEntity[];
  parameterMap: Map<string, string>; // entityId → paramName
}

/**
 * Orchestrates auto-generation of complete technical drawings from Lift parameters.
 * All generated entities have autoGenerated=true and sourceParam set.
 */
export class AutoDrawingGenerator {
  private entityModel: EntityModel;
  private blockLibrary: BlockLibrary;
  private autoGeneratedIds: Set<string> = new Set();
  private parameterMapping: Map<string, string> = new Map();

  constructor(entityModel: EntityModel, blockLibrary: BlockLibrary) {
    this.entityModel = entityModel;
    this.blockLibrary = blockLibrary;
  }

  /** Generate a specific drawing type. */
  generate(type: DrawingType, params: LiftParams): GenerationResult {
    switch (type) {
      case 'cross-section':
        return this.generateCrossSection(params);
      case 'longitudinal':
        return this.generateLongitudinalSection(params);
      case 'machine-room':
        return this.generateMachineRoom(params);
      case 'cabin-plan':
        return this.generateCabinPlan(params);
      case 'pit-detail':
        return this.generatePitDetail(params);
      case 'overhead-detail':
        return this.generateOverheadDetail(params);
      default:
        return { entities: [], parameterMap: new Map() };
    }
  }

  generateCrossSection(params: LiftParams): GenerationResult {
    const gen = new CrossSectionGenerator(this.blockLibrary);
    const result = gen.generate(params);
    this.addToModel(result);
    return result;
  }

  generateLongitudinalSection(params: LiftParams): GenerationResult {
    const gen = new LongitudinalGenerator(this.blockLibrary);
    const result = gen.generate(params);
    this.addToModel(result);
    return result;
  }

  generateMachineRoom(params: LiftParams): GenerationResult {
    const gen = new MachineRoomGenerator(this.blockLibrary);
    const result = gen.generate(params);
    this.addToModel(result);
    return result;
  }

  generateCabinPlan(params: LiftParams): GenerationResult {
    const gen = new CabinPlanGenerator(this.blockLibrary);
    const result = gen.generate(params);
    this.addToModel(result);
    return result;
  }

  generatePitDetail(params: LiftParams): GenerationResult {
    const gen = new PitDetailGenerator();
    const result = gen.generate(params);
    this.addToModel(result);
    return result;
  }

  generateOverheadDetail(params: LiftParams): GenerationResult {
    const gen = new OverheadDetailGenerator();
    const result = gen.generate(params);
    this.addToModel(result);
    return result;
  }

  /** Get all auto-generated entity IDs. */
  getAutoGeneratedEntityIds(): string[] {
    return Array.from(this.autoGeneratedIds);
  }

  /** Get the parameter mapping (entityId → paramName). */
  getParameterMapping(): Map<string, string> {
    return new Map(this.parameterMapping);
  }

  /** Clear all auto-generated entities from the model. */
  clearAutoGenerated(): void {
    for (const id of this.autoGeneratedIds) {
      this.entityModel.removeEntity(id);
    }
    this.autoGeneratedIds.clear();
    this.parameterMapping.clear();
  }

  private addToModel(result: GenerationResult): void {
    for (const entity of result.entities) {
      this.entityModel.addEntity(entity);
      this.autoGeneratedIds.add(entity.id);
    }
    for (const [entityId, paramName] of result.parameterMap) {
      this.parameterMapping.set(entityId, paramName);
    }
  }
}
