import { v4 } from 'uuid';
import type {
  CadEntity,
  LiftParams,
  PolylineEntity,
  LineEntity,
  DimensionEntity,
  Point2D,
} from '../core/types';
import type { BlockLibrary } from '../blocks/BlockLibrary';
import type { GenerationResult } from './AutoDrawingGenerator';

/**
 * Generates cabin plan: cabin walls, door opening, handrails, button panel, dimensions.
 */
export class CabinPlanGenerator {
  constructor(private blockLibrary: BlockLibrary) {}

  generate(params: LiftParams): GenerationResult {
    const entities: CadEntity[] = [];
    const parameterMap = new Map<string, string>();

    const cabinW = params.kabinGenisligi;
    const cabinD = params.kabinDerinligi;
    const doorW = params.kapiGenisligi;
    const halfW = cabinW / 2;

    // Cabin walls
    const walls = makePolyline(
      [
        { x: -halfW, y: 0 },
        { x: halfW, y: 0 },
        { x: halfW, y: cabinD },
        { x: -halfW, y: cabinD },
      ],
      true, 'Cabin', '#2563EB', 0.35, 'kabinGenisligi'
    );
    entities.push(walls);
    parameterMap.set(walls.id, 'kabinGenisligi');

    // Door opening
    const halfDoor = doorW / 2;
    const doorLine: LineEntity = {
      id: v4(), type: 'line',
      start: { x: -halfDoor, y: 0 },
      end: { x: halfDoor, y: 0 },
      layerName: 'Doors', color: '#EA580C', lineType: 'dashed', lineWeight: 0.35,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'kapiGenisligi',
    };
    entities.push(doorLine);
    parameterMap.set(doorLine.id, 'kapiGenisligi');

    // Handrails
    const handrailOffset = 50;
    const handrailStart = cabinD * 0.2;
    const handrailEnd = cabinD * 0.8;

    const leftHandrail: LineEntity = {
      id: v4(), type: 'line',
      start: { x: -halfW + handrailOffset, y: handrailStart },
      end: { x: -halfW + handrailOffset, y: handrailEnd },
      layerName: 'Cabin', color: '#2563EB', lineType: 'continuous', lineWeight: 0.25,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'kabinDerinligi',
    };
    entities.push(leftHandrail);

    const rightHandrail: LineEntity = {
      id: v4(), type: 'line',
      start: { x: halfW - handrailOffset, y: handrailStart },
      end: { x: halfW - handrailOffset, y: handrailEnd },
      layerName: 'Cabin', color: '#2563EB', lineType: 'continuous', lineWeight: 0.25,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'kabinDerinligi',
    };
    entities.push(rightHandrail);

    // Button panel
    const panelW = 60;
    const panelH = 120;
    const panelX = halfW - handrailOffset - panelW;
    const panelY = cabinD * 0.4;
    const buttonPanel = makePolyline(
      [
        { x: panelX, y: panelY },
        { x: panelX + panelW, y: panelY },
        { x: panelX + panelW, y: panelY + panelH },
        { x: panelX, y: panelY + panelH },
      ],
      true, 'Cabin', '#2563EB', 0.18, 'kabinGenisligi'
    );
    entities.push(buttonPanel);

    // Dimensions
    // Cabin width
    const dimW = makeDimension(
      { x: -halfW, y: cabinD }, { x: halfW, y: cabinD },
      { x: 0, y: cabinD + 30 },
      cabinW, 'kabinGenisligi'
    );
    entities.push(dimW);
    parameterMap.set(dimW.id, 'kabinGenisligi');

    // Cabin depth
    const dimD = makeDimension(
      { x: -halfW, y: 0 }, { x: -halfW, y: cabinD },
      { x: -halfW - 30, y: cabinD / 2 },
      cabinD, 'kabinDerinligi'
    );
    entities.push(dimD);
    parameterMap.set(dimD.id, 'kabinDerinligi');

    // Door width
    const dimDoor = makeDimension(
      { x: -halfDoor, y: 0 }, { x: halfDoor, y: 0 },
      { x: 0, y: -25 },
      doorW, 'kapiGenisligi'
    );
    entities.push(dimDoor);
    parameterMap.set(dimDoor.id, 'kapiGenisligi');

    return { entities, parameterMap };
  }
}

function makePolyline(
  vertices: Point2D[], closed: boolean,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): PolylineEntity {
  return {
    id: v4(), type: 'polyline', vertices, closed,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeDimension(
  defPoint1: Point2D, defPoint2: Point2D, dimLinePoint: Point2D,
  measurementValue: number, sourceParam: string
): DimensionEntity {
  return {
    id: v4(), type: 'dimension', dimensionType: 'linear',
    defPoint1, defPoint2, dimLinePoint, measurementValue,
    textHeight: 2.5, arrowSize: 2.5, extensionLineOffset: 1.5, decimalPrecision: 0,
    layerName: 'Dimensions', color: '#06B6D4', lineType: 'continuous', lineWeight: 0.18,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}
