import { v4 } from 'uuid';
import type {
  CadEntity,
  LiftParams,
  PolylineEntity,
  LineEntity,
  DimensionEntity,
  TextEntity,
  Point2D,
} from '../core/types';
import type { BlockLibrary } from '../blocks/BlockLibrary';
import type { GenerationResult } from './AutoDrawingGenerator';

/**
 * Generates longitudinal section: pit, floor levels, cabin, counterweight,
 * travel distance, overhead clearance, machine room outline.
 */
export class LongitudinalGenerator {
  constructor(private blockLibrary: BlockLibrary) {}

  generate(params: LiftParams): GenerationResult {
    const entities: CadEntity[] = [];
    const parameterMap = new Map<string, string>();

    const shaftW = params.kuyuGenisligi;
    const pitDepth = params.kuyuDibi;
    const overhead = params.kuyuKafa;
    const cabinW = params.kabinGenisligi;
    const cabinH = params.kabinYuksekligi;
    const floors = params.floors ?? [];

    // Compute total travel
    let totalTravel = 0;
    for (const floor of floors) {
      totalTravel += floor.katYuksekligi;
    }
    if (floors.length > 0) {
      totalTravel -= floors[0].katYuksekligi; // first floor height is ground level
    }

    const totalHeight = pitDepth + totalTravel + overhead;
    const halfW = shaftW / 2;

    // Shaft walls (left and right vertical lines)
    const leftWall = makeLine(
      { x: -halfW, y: -pitDepth }, { x: -halfW, y: totalTravel + overhead },
      'Shaft', '#808080', 0.50, 'kuyuGenisligi'
    );
    entities.push(leftWall);
    parameterMap.set(leftWall.id, 'kuyuGenisligi');

    const rightWall = makeLine(
      { x: halfW, y: -pitDepth }, { x: halfW, y: totalTravel + overhead },
      'Shaft', '#808080', 0.50, 'kuyuGenisligi'
    );
    entities.push(rightWall);
    parameterMap.set(rightWall.id, 'kuyuGenisligi');

    // Pit floor
    const pitFloor = makeLine(
      { x: -halfW, y: -pitDepth }, { x: halfW, y: -pitDepth },
      'Shaft', '#808080', 0.50, 'kuyuDibi'
    );
    entities.push(pitFloor);
    parameterMap.set(pitFloor.id, 'kuyuDibi');

    // Top of shaft
    const topLine = makeLine(
      { x: -halfW, y: totalTravel + overhead }, { x: halfW, y: totalTravel + overhead },
      'Shaft', '#808080', 0.50, 'kuyuKafa'
    );
    entities.push(topLine);
    parameterMap.set(topLine.id, 'kuyuKafa');

    // Floor levels
    let currentY = 0;
    for (let i = 0; i < floors.length; i++) {
      if (i > 0) {
        currentY += floors[i].katYuksekligi;
      }

      // Floor line
      const floorLine = makeLine(
        { x: -halfW - 30, y: currentY }, { x: halfW + 30, y: currentY },
        'Shaft', '#808080', 0.18, 'durakSayisi'
      );
      floorLine.lineType = 'dashed';
      entities.push(floorLine);

      // Floor label
      const label: TextEntity = {
        id: v4(), type: 'text',
        position: { x: halfW + 40, y: currentY },
        content: floors[i].katRumuz || `K${floors[i].katNo}`,
        fontSize: 3, fontFamily: 'Arial', fontWeight: 'normal', fontStyle: 'normal',
        alignment: 'left', rotation: 0,
        layerName: 'Text', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.18,
        visible: true, locked: false, autoGenerated: true, sourceParam: 'durakSayisi',
      };
      entities.push(label);
    }

    // Cabin at ground floor (y=0)
    const halfCabinW = cabinW / 2;
    const cabinOutline = makePolyline(
      [
        { x: -halfCabinW, y: 0 },
        { x: halfCabinW, y: 0 },
        { x: halfCabinW, y: cabinH },
        { x: -halfCabinW, y: cabinH },
      ],
      true, 'Cabin', '#2563EB', 0.35, 'kabinYuksekligi'
    );
    entities.push(cabinOutline);
    parameterMap.set(cabinOutline.id, 'kabinYuksekligi');

    // Counterweight (at top when cabin is at bottom)
    const cwW = 150;
    const cwH = cabinH * 0.6;
    const cwY = totalTravel - cwH;
    const cwOutline = makePolyline(
      [
        { x: halfW - cwW - 30, y: cwY },
        { x: halfW - 30, y: cwY },
        { x: halfW - 30, y: cwY + cwH },
        { x: halfW - cwW - 30, y: cwY + cwH },
      ],
      true, 'Counterweight', '#4B5563', 0.25, 'beyanYuk'
    );
    entities.push(cwOutline);
    parameterMap.set(cwOutline.id, 'beyanYuk');

    // Dimensions
    // Pit depth
    const dimPit = makeDimension(
      { x: -halfW, y: -pitDepth }, { x: -halfW, y: 0 },
      { x: -halfW - 50, y: -pitDepth / 2 },
      pitDepth, 'kuyuDibi'
    );
    entities.push(dimPit);
    parameterMap.set(dimPit.id, 'kuyuDibi');

    // Overhead
    const dimOverhead = makeDimension(
      { x: -halfW, y: totalTravel }, { x: -halfW, y: totalTravel + overhead },
      { x: -halfW - 50, y: totalTravel + overhead / 2 },
      overhead, 'kuyuKafa'
    );
    entities.push(dimOverhead);
    parameterMap.set(dimOverhead.id, 'kuyuKafa');

    // Travel distance
    if (totalTravel > 0) {
      const dimTravel = makeDimension(
        { x: -halfW, y: 0 }, { x: -halfW, y: totalTravel },
        { x: -halfW - 80, y: totalTravel / 2 },
        totalTravel, 'durakSayisi'
      );
      entities.push(dimTravel);
      parameterMap.set(dimTravel.id, 'durakSayisi');
    }

    return { entities, parameterMap };
  }
}

function makePolyline(
  vertices: Point2D[], closed: boolean,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): PolylineEntity {
  return {
    id: v4(), type: 'polyline', vertices, closed,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeLine(
  start: Point2D, end: Point2D,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): LineEntity {
  return {
    id: v4(), type: 'line', start, end,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeDimension(
  defPoint1: Point2D, defPoint2: Point2D, dimLinePoint: Point2D,
  measurementValue: number, sourceParam: string
): DimensionEntity {
  return {
    id: v4(), type: 'dimension', dimensionType: 'linear',
    defPoint1, defPoint2, dimLinePoint, measurementValue,
    textHeight: 2.5, arrowSize: 2.5, extensionLineOffset: 1.5, decimalPrecision: 0,
    layerName: 'Dimensions', color: '#06B6D4', lineType: 'continuous', lineWeight: 0.18,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}
