import { v4 } from 'uuid';
import type {
  CadEntity,
  LiftParams,
  PolylineEntity,
  CircleEntity,
  LineEntity,
  DimensionEntity,
  TextEntity,
  Point2D,
} from '../core/types';
import type { BlockLibrary } from '../blocks/BlockLibrary';
import type { GenerationResult } from './AutoDrawingGenerator';

/**
 * Generates machine room plan: room walls, traction machine, deflection sheave,
 * control panel, governor, access door, dimensions.
 */
export class MachineRoomGenerator {
  constructor(private blockLibrary: BlockLibrary) {}

  generate(params: LiftParams): GenerationResult {
    const entities: CadEntity[] = [];
    const parameterMap = new Map<string, string>();

    const shaftW = params.kuyuGenisligi;
    const shaftD = params.kuyuDerinligi;

    // Machine room is typically larger than shaft
    const roomW = shaftW + 600;
    const roomD = shaftD + 800;
    const halfW = roomW / 2;
    const halfD = roomD / 2;

    // Room walls
    const walls = makePolyline(
      [
        { x: -halfW, y: -halfD },
        { x: halfW, y: -halfD },
        { x: halfW, y: halfD },
        { x: -halfW, y: halfD },
      ],
      true, 'Shaft', '#808080', 0.50, 'kuyuGenisligi'
    );
    entities.push(walls);
    parameterMap.set(walls.id, 'kuyuGenisligi');

    // Traction machine (circle)
    const machineRadius = 200;
    const machine: CircleEntity = {
      id: v4(), type: 'circle',
      center: { x: 0, y: 100 },
      radius: machineRadius,
      layerName: '0', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.35,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'beyanYuk',
    };
    entities.push(machine);
    parameterMap.set(machine.id, 'beyanYuk');

    // Deflection sheave
    const sheaveRadius = 150;
    const sheave: CircleEntity = {
      id: v4(), type: 'circle',
      center: { x: -300, y: 100 },
      radius: sheaveRadius,
      layerName: '0', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.25,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'beyanYuk',
    };
    entities.push(sheave);
    parameterMap.set(sheave.id, 'beyanYuk');

    // Control panel (rectangle)
    const panelW = 400;
    const panelH = 200;
    const panel = makePolyline(
      [
        { x: halfW - panelW - 50, y: -halfD + 50 },
        { x: halfW - 50, y: -halfD + 50 },
        { x: halfW - 50, y: -halfD + 50 + panelH },
        { x: halfW - panelW - 50, y: -halfD + 50 + panelH },
      ],
      true, '0', '#FFFFFF', 0.35, 'beyanYuk'
    );
    entities.push(panel);

    // Panel label
    const panelLabel: TextEntity = {
      id: v4(), type: 'text',
      position: { x: halfW - panelW / 2 - 50, y: -halfD + 50 + panelH / 2 },
      content: 'CTRL',
      fontSize: 5, fontFamily: 'Arial', fontWeight: 'bold', fontStyle: 'normal',
      alignment: 'center', rotation: 0,
      layerName: 'Text', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.18,
      visible: true, locked: false, autoGenerated: true,
    };
    entities.push(panelLabel);

    // Governor (small circle)
    const govRadius = 80;
    const governor: CircleEntity = {
      id: v4(), type: 'circle',
      center: { x: -halfW + 150, y: -halfD + 150 },
      radius: govRadius,
      layerName: '0', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.25,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'beyanYuk',
    };
    entities.push(governor);
    parameterMap.set(governor.id, 'beyanYuk');

    // Access door (gap in wall)
    const doorW = 900;
    const doorLine: LineEntity = {
      id: v4(), type: 'line',
      start: { x: -doorW / 2, y: -halfD },
      end: { x: doorW / 2, y: -halfD },
      layerName: 'Doors', color: '#EA580C', lineType: 'dashed', lineWeight: 0.35,
      visible: true, locked: false, autoGenerated: true,
    };
    entities.push(doorLine);

    // Dimensions
    const dimRoomW = makeDimension(
      { x: -halfW, y: -halfD }, { x: halfW, y: -halfD },
      { x: 0, y: -halfD - 40 },
      roomW, 'kuyuGenisligi'
    );
    entities.push(dimRoomW);
    parameterMap.set(dimRoomW.id, 'kuyuGenisligi');

    const dimRoomD = makeDimension(
      { x: halfW, y: -halfD }, { x: halfW, y: halfD },
      { x: halfW + 40, y: 0 },
      roomD, 'kuyuDerinligi'
    );
    entities.push(dimRoomD);
    parameterMap.set(dimRoomD.id, 'kuyuDerinligi');

    return { entities, parameterMap };
  }
}

function makePolyline(
  vertices: Point2D[], closed: boolean,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): PolylineEntity {
  return {
    id: v4(), type: 'polyline', vertices, closed,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeDimension(
  defPoint1: Point2D, defPoint2: Point2D, dimLinePoint: Point2D,
  measurementValue: number, sourceParam: string
): DimensionEntity {
  return {
    id: v4(), type: 'dimension', dimensionType: 'linear',
    defPoint1, defPoint2, dimLinePoint, measurementValue,
    textHeight: 2.5, arrowSize: 2.5, extensionLineOffset: 1.5, decimalPrecision: 0,
    layerName: 'Dimensions', color: '#06B6D4', lineType: 'continuous', lineWeight: 0.18,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}
