import { v4 } from 'uuid';
import type {
  CadEntity,
  LiftParams,
  PolylineEntity,
  LineEntity,
  DimensionEntity,
  TextEntity,
  Point2D,
} from '../core/types';
import type { GenerationResult } from './AutoDrawingGenerator';

/**
 * Generates overhead detail drawing per EN81-1:
 * top floor landing, overhead clearance, machine beam positions, minimum overhead dimensions.
 */
export class OverheadDetailGenerator {
  generate(params: LiftParams): GenerationResult {
    const entities: CadEntity[] = [];
    const parameterMap = new Map<string, string>();

    const shaftW = params.kuyuGenisligi;
    const overhead = params.kuyuKafa;
    const cabinH = params.kabinYuksekligi;
    const halfW = shaftW / 2;

    // EN81-1 minimum overhead requirements
    const minOverhead = Math.max(3600, overhead); // minimum 3600mm per EN81-1

    // Compute total travel for positioning
    let totalTravel = 0;
    const floors = params.floors ?? [];
    for (let i = 1; i < floors.length; i++) {
      totalTravel += floors[i].katYuksekligi;
    }

    const topFloorY = totalTravel;
    const topShaftY = topFloorY + overhead;

    // Shaft walls (top portion)
    const leftWall = makeLine(
      { x: -halfW, y: topFloorY - 500 }, { x: -halfW, y: topShaftY },
      'Shaft', '#808080', 0.50, 'kuyuGenisligi'
    );
    entities.push(leftWall);
    parameterMap.set(leftWall.id, 'kuyuGenisligi');

    const rightWall = makeLine(
      { x: halfW, y: topFloorY - 500 }, { x: halfW, y: topShaftY },
      'Shaft', '#808080', 0.50, 'kuyuGenisligi'
    );
    entities.push(rightWall);
    parameterMap.set(rightWall.id, 'kuyuGenisligi');

    // Top of shaft (ceiling)
    const ceiling = makeLine(
      { x: -halfW, y: topShaftY }, { x: halfW, y: topShaftY },
      'Shaft', '#808080', 0.50, 'kuyuKafa'
    );
    entities.push(ceiling);
    parameterMap.set(ceiling.id, 'kuyuKafa');

    // Top floor landing level
    const topFloorLine = makeLine(
      { x: -halfW - 20, y: topFloorY }, { x: halfW + 20, y: topFloorY },
      'Shaft', '#808080', 0.35, 'kuyuKafa'
    );
    entities.push(topFloorLine);

    // Top floor label
    const topFloorLabel: TextEntity = {
      id: v4(), type: 'text',
      position: { x: halfW + 30, y: topFloorY },
      content: floors.length > 0 ? floors[floors.length - 1].katRumuz || 'Top' : 'Top',
      fontSize: 3, fontFamily: 'Arial', fontWeight: 'normal', fontStyle: 'normal',
      alignment: 'left', rotation: 0,
      layerName: 'Text', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.18,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'kuyuKafa',
    };
    entities.push(topFloorLabel);

    // Cabin at top floor (outline)
    const halfCabinW = params.kabinGenisligi / 2;
    const cabinOutline = makePolyline(
      [
        { x: -halfCabinW, y: topFloorY },
        { x: halfCabinW, y: topFloorY },
        { x: halfCabinW, y: topFloorY + cabinH },
        { x: -halfCabinW, y: topFloorY + cabinH },
      ],
      true, 'Cabin', '#2563EB', 0.35, 'kabinYuksekligi'
    );
    entities.push(cabinOutline);
    parameterMap.set(cabinOutline.id, 'kabinYuksekligi');

    // Machine beam positions (horizontal lines at top)
    const beamY1 = topShaftY - 100;
    const beamY2 = topShaftY - 200;
    for (const by of [beamY1, beamY2]) {
      const beam = makeLine(
        { x: -halfW, y: by }, { x: halfW, y: by },
        '0', '#FFFFFF', 0.25, 'kuyuKafa'
      );
      beam.lineType = 'center';
      entities.push(beam);
    }

    // Overhead clearance (from top of cabin to ceiling)
    const clearance = topShaftY - (topFloorY + cabinH);

    // Dimensions
    // Overhead
    const dimOverhead = makeDimension(
      { x: -halfW, y: topFloorY }, { x: -halfW, y: topShaftY },
      { x: -halfW - 40, y: topFloorY + overhead / 2 },
      overhead, 'kuyuKafa'
    );
    entities.push(dimOverhead);
    parameterMap.set(dimOverhead.id, 'kuyuKafa');

    // Cabin height
    const dimCabinH = makeDimension(
      { x: halfCabinW, y: topFloorY }, { x: halfCabinW, y: topFloorY + cabinH },
      { x: halfCabinW + 30, y: topFloorY + cabinH / 2 },
      cabinH, 'kabinYuksekligi'
    );
    entities.push(dimCabinH);
    parameterMap.set(dimCabinH.id, 'kabinYuksekligi');

    // Free clearance above cabin
    if (clearance > 0) {
      const dimClearance = makeDimension(
        { x: 0, y: topFloorY + cabinH }, { x: 0, y: topShaftY },
        { x: halfW - 60, y: topFloorY + cabinH + clearance / 2 },
        clearance, 'kuyuKafa'
      );
      entities.push(dimClearance);
    }

    // EN81-1 minimum annotation
    const minLabel: TextEntity = {
      id: v4(), type: 'text',
      position: { x: -halfW - 60, y: topShaftY + 10 },
      content: `Min. overhead: ${minOverhead}mm (EN81-1)`,
      fontSize: 2, fontFamily: 'Arial', fontWeight: 'normal', fontStyle: 'italic',
      alignment: 'left', rotation: 0,
      layerName: 'Text', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.18,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'kuyuKafa',
    };
    entities.push(minLabel);

    return { entities, parameterMap };
  }
}

function makePolyline(
  vertices: Point2D[], closed: boolean,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): PolylineEntity {
  return {
    id: v4(), type: 'polyline', vertices, closed,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeLine(
  start: Point2D, end: Point2D,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): LineEntity {
  return {
    id: v4(), type: 'line', start, end,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeDimension(
  defPoint1: Point2D, defPoint2: Point2D, dimLinePoint: Point2D,
  measurementValue: number, sourceParam: string
): DimensionEntity {
  return {
    id: v4(), type: 'dimension', dimensionType: 'linear',
    defPoint1, defPoint2, dimLinePoint, measurementValue,
    textHeight: 2.5, arrowSize: 2.5, extensionLineOffset: 1.5, decimalPrecision: 0,
    layerName: 'Dimensions', color: '#06B6D4', lineType: 'continuous', lineWeight: 0.18,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}
