import { v4 } from 'uuid';
import type {
  CadEntity,
  LiftParams,
  PolylineEntity,
  LineEntity,
  DimensionEntity,
  TextEntity,
  Point2D,
} from '../core/types';
import type { GenerationResult } from './AutoDrawingGenerator';

/**
 * Generates pit detail drawing per EN81-1:
 * pit floor, buffer positions, safety gear clearance, minimum pit depth dimensions.
 */
export class PitDetailGenerator {
  generate(params: LiftParams): GenerationResult {
    const entities: CadEntity[] = [];
    const parameterMap = new Map<string, string>();

    const shaftW = params.kuyuGenisligi;
    const pitDepth = params.kuyuDibi;
    const cabinW = params.kabinGenisligi;
    const cabinD = params.kabinDerinligi;
    const halfW = shaftW / 2;

    // EN81-1 minimum pit depth requirements
    const minPitDepth = Math.max(1200, pitDepth); // minimum 1200mm per EN81-1

    // Shaft walls in pit area
    const leftWall = makeLine(
      { x: -halfW, y: -pitDepth }, { x: -halfW, y: 200 },
      'Shaft', '#808080', 0.50, 'kuyuGenisligi'
    );
    entities.push(leftWall);
    parameterMap.set(leftWall.id, 'kuyuGenisligi');

    const rightWall = makeLine(
      { x: halfW, y: -pitDepth }, { x: halfW, y: 200 },
      'Shaft', '#808080', 0.50, 'kuyuGenisligi'
    );
    entities.push(rightWall);
    parameterMap.set(rightWall.id, 'kuyuGenisligi');

    // Pit floor
    const pitFloor = makeLine(
      { x: -halfW, y: -pitDepth }, { x: halfW, y: -pitDepth },
      'Shaft', '#808080', 0.50, 'kuyuDibi'
    );
    entities.push(pitFloor);
    parameterMap.set(pitFloor.id, 'kuyuDibi');

    // Ground floor level
    const groundLevel = makeLine(
      { x: -halfW - 20, y: 0 }, { x: halfW + 20, y: 0 },
      'Shaft', '#808080', 0.35, 'kuyuDibi'
    );
    entities.push(groundLevel);

    // Buffer positions (two buffers under cabin)
    const bufferSpacing = cabinW * 0.4;
    const bufferHeight = 150;
    const bufferWidth = 80;

    for (const bx of [-bufferSpacing / 2, bufferSpacing / 2]) {
      const buffer = makePolyline(
        [
          { x: bx - bufferWidth / 2, y: -pitDepth },
          { x: bx + bufferWidth / 2, y: -pitDepth },
          { x: bx + bufferWidth / 2, y: -pitDepth + bufferHeight },
          { x: bx - bufferWidth / 2, y: -pitDepth + bufferHeight },
        ],
        true, '0', '#FFFFFF', 0.25, 'kuyuDibi'
      );
      entities.push(buffer);
    }

    // Safety gear clearance zone (dashed rectangle)
    const safetyGearClearance = 300; // mm minimum clearance
    const sgZone = makePolyline(
      [
        { x: -halfW + 20, y: -pitDepth },
        { x: halfW - 20, y: -pitDepth },
        { x: halfW - 20, y: -pitDepth + safetyGearClearance },
        { x: -halfW + 20, y: -pitDepth + safetyGearClearance },
      ],
      true, '0', '#FFFFFF', 0.18, 'kuyuDibi'
    );
    sgZone.lineType = 'dashed';
    entities.push(sgZone);

    // Safety gear clearance label
    const sgLabel: TextEntity = {
      id: v4(), type: 'text',
      position: { x: 0, y: -pitDepth + safetyGearClearance / 2 },
      content: 'Safety Gear Clearance',
      fontSize: 2.5, fontFamily: 'Arial', fontWeight: 'normal', fontStyle: 'normal',
      alignment: 'center', rotation: 0,
      layerName: 'Text', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.18,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'kuyuDibi',
    };
    entities.push(sgLabel);

    // Dimensions
    // Pit depth
    const dimPit = makeDimension(
      { x: -halfW, y: -pitDepth }, { x: -halfW, y: 0 },
      { x: -halfW - 40, y: -pitDepth / 2 },
      pitDepth, 'kuyuDibi'
    );
    entities.push(dimPit);
    parameterMap.set(dimPit.id, 'kuyuDibi');

    // Buffer height
    const dimBuffer = makeDimension(
      { x: 0, y: -pitDepth }, { x: 0, y: -pitDepth + bufferHeight },
      { x: halfW - 60, y: -pitDepth + bufferHeight / 2 },
      bufferHeight, 'kuyuDibi'
    );
    entities.push(dimBuffer);

    // EN81-1 minimum annotation
    const minLabel: TextEntity = {
      id: v4(), type: 'text',
      position: { x: -halfW - 60, y: -pitDepth - 15 },
      content: `Min. pit: ${minPitDepth}mm (EN81-1)`,
      fontSize: 2, fontFamily: 'Arial', fontWeight: 'normal', fontStyle: 'italic',
      alignment: 'left', rotation: 0,
      layerName: 'Text', color: '#FFFFFF', lineType: 'continuous', lineWeight: 0.18,
      visible: true, locked: false, autoGenerated: true, sourceParam: 'kuyuDibi',
    };
    entities.push(minLabel);

    return { entities, parameterMap };
  }
}

function makePolyline(
  vertices: Point2D[], closed: boolean,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): PolylineEntity {
  return {
    id: v4(), type: 'polyline', vertices, closed,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeLine(
  start: Point2D, end: Point2D,
  layerName: string, color: string, lineWeight: number, sourceParam: string
): LineEntity {
  return {
    id: v4(), type: 'line', start, end,
    layerName, color, lineType: 'continuous', lineWeight,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}

function makeDimension(
  defPoint1: Point2D, defPoint2: Point2D, dimLinePoint: Point2D,
  measurementValue: number, sourceParam: string
): DimensionEntity {
  return {
    id: v4(), type: 'dimension', dimensionType: 'linear',
    defPoint1, defPoint2, dimLinePoint, measurementValue,
    textHeight: 2.5, arrowSize: 2.5, extensionLineOffset: 1.5, decimalPrecision: 0,
    layerName: 'Dimensions', color: '#06B6D4', lineType: 'continuous', lineWeight: 0.18,
    visible: true, locked: false, autoGenerated: true, sourceParam,
  };
}
