import { v4 as uuid } from 'uuid';
import type { CadEntity, TitleBlockData, LineEntity, TextEntity, PolylineEntity } from '../core/types';

/**
 * Generates title block entities (border rect, text fields for company/project/engineer info)
 * and returns them for addition to the entity model on the TitleBlock layer.
 */
export function generateTitleBlock(
  data: TitleBlockData,
  originX = 0,
  originY = -50
): CadEntity[] {
  const entities: CadEntity[] = [];
  const layer = 'TitleBlock';
  const color = '#A855F7';
  const base = { layerName: layer, color, lineType: 'continuous' as const, lineWeight: 0.5, visible: true, locked: false, autoGenerated: true, sourceParam: undefined };

  const w = 841; // A1 width in mm (scaled)
  const h = 594;
  const tbH = 60; // title block height
  const tbY = originY;
  const tbX = originX;

  // Outer border
  entities.push({
    ...base,
    id: uuid(),
    type: 'polyline',
    vertices: [
      { x: tbX, y: tbY },
      { x: tbX + w, y: tbY },
      { x: tbX + w, y: tbY + h },
      { x: tbX, y: tbY + h },
    ],
    closed: true,
  } as PolylineEntity);

  // Title block box at bottom
  entities.push({
    ...base,
    id: uuid(),
    type: 'polyline',
    vertices: [
      { x: tbX, y: tbY },
      { x: tbX + w, y: tbY },
      { x: tbX + w, y: tbY + tbH },
      { x: tbX, y: tbY + tbH },
    ],
    closed: true,
  } as PolylineEntity);

  // Vertical dividers in title block
  const col1 = tbX + w * 0.35;
  const col2 = tbX + w * 0.65;
  entities.push(makeLine(col1, tbY, col1, tbY + tbH, base));
  entities.push(makeLine(col2, tbY, col2, tbY + tbH, base));

  // Horizontal divider
  const midY = tbY + tbH / 2;
  entities.push(makeLine(tbX, midY, tbX + w, midY, base));

  // Text entries
  const textBase = { ...base, lineWeight: 0.18, fontFamily: 'sans-serif', fontWeight: 'normal' as const, fontStyle: 'normal' as const, alignment: 'left' as const, rotation: 0 };

  // Company info (top-left cell)
  entities.push(makeText(tbX + 5, midY + 18, data.companyName, 5, { ...textBase, fontWeight: 'bold' }));
  entities.push(makeText(tbX + 5, midY + 8, data.companyAddress, 3.5, textBase));
  entities.push(makeText(tbX + 5, midY + 3, data.companyPhone, 3.5, textBase));

  // Project info (top-center cell)
  entities.push(makeText(col1 + 5, midY + 18, data.projectName, 5, { ...textBase, fontWeight: 'bold' }));
  entities.push(makeText(col1 + 5, midY + 8, data.drawingTitle, 4, textBase));
  entities.push(makeText(col1 + 5, midY + 3, `Ölçek: ${data.scale}`, 3.5, textBase));

  // Drawing info (top-right cell)
  entities.push(makeText(col2 + 5, midY + 18, `Tarih: ${data.date}`, 3.5, textBase));
  entities.push(makeText(col2 + 5, midY + 10, `Rev: ${data.revision}`, 3.5, textBase));
  entities.push(makeText(col2 + 5, midY + 3, `No: ${data.drawingNumber}`, 3.5, textBase));

  // Engineers (bottom row)
  entities.push(makeText(tbX + 5, tbY + 18, `Mak. Müh.: ${data.mechanicalEngineerName}`, 3.5, textBase));
  entities.push(makeText(tbX + 5, tbY + 8, `SMM: ${data.mechanicalEngineerSMM}`, 3, textBase));
  entities.push(makeText(col1 + 5, tbY + 18, `Elk. Müh.: ${data.electricalEngineerName}`, 3.5, textBase));
  entities.push(makeText(col1 + 5, tbY + 8, `SMM: ${data.electricalEngineerSMM}`, 3, textBase));

  return entities;
}

function makeLine(x1: number, y1: number, x2: number, y2: number, base: any): LineEntity {
  return {
    ...base,
    id: uuid(),
    type: 'line',
    start: { x: x1, y: y1 },
    end: { x: x2, y: y2 },
  };
}

function makeText(x: number, y: number, content: string, fontSize: number, base: any): TextEntity {
  return {
    ...base,
    id: uuid(),
    type: 'text',
    position: { x, y },
    content: content || '',
    fontSize,
  };
}
