import { v4 } from 'uuid';
import type { CadEntity, CircleEntity, PolylineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Buffer parametric block: cylinder cross-section (circle + rectangle).
 */
export class BufferBlock extends BaseParametricBlock {
  readonly name = 'Buffer';
  readonly displayName = 'Buffer';
  readonly parameterBindings: Record<string, string> = {
    load: 'beyanYuk',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [];

  generate(params: Record<string, number>): CadEntity[] {
    const load = params.load ?? 630;
    const entities: CadEntity[] = [];

    const radius = 40 + load * 0.01;
    const height = 100 + load * 0.05;

    // Circle (top view)
    const circle: CircleEntity = {
      id: v4(),
      type: 'circle',
      center: { x: 0, y: height },
      radius,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(circle);

    // Rectangle (side view)
    const rect: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -radius, y: 0 },
        { x: radius, y: 0 },
        { x: radius, y: height },
        { x: -radius, y: height },
      ],
      closed: true,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(rect);

    return entities;
  }
}
