import { v4 } from 'uuid';
import type { CadEntity, PolylineEntity, LineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Cabin parametric block: walls polyline + door opening + handrails + button panel.
 * Bound to kabinGenisligi, kabinDerinligi, kapiGenisligi.
 */
export class CabinBlock extends BaseParametricBlock {
  readonly name = 'Cabin';
  readonly displayName = 'Cabin';
  readonly parameterBindings: Record<string, string> = {
    width: 'kabinGenisligi',
    depth: 'kabinDerinligi',
    doorWidth: 'kapiGenisligi',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [
    { tag: 'WIDTH', prompt: 'Cabin width (mm)', defaultValue: '1100', position: { x: 0, y: -20 }, textHeight: 2.5, visible: true },
    { tag: 'DEPTH', prompt: 'Cabin depth (mm)', defaultValue: '1400', position: { x: 0, y: -25 }, textHeight: 2.5, visible: true },
  ];

  generate(params: Record<string, number>): CadEntity[] {
    const w = params.width ?? 1100;
    const d = params.depth ?? 1400;
    const doorW = params.doorWidth ?? 800;
    const entities: CadEntity[] = [];

    // Cabin walls (closed polyline) — origin at center-front
    const halfW = w / 2;
    const walls: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -halfW, y: 0 },
        { x: halfW, y: 0 },
        { x: halfW, y: d },
        { x: -halfW, y: d },
      ],
      closed: true,
      layerName: 'Cabin',
      color: '#2563EB',
      lineType: 'continuous',
      lineWeight: 0.35,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kabinGenisligi',
    };
    entities.push(walls);

    // Door opening (gap in front wall)
    const halfDoor = doorW / 2;
    const doorLine: LineEntity = {
      id: v4(),
      type: 'line',
      start: { x: -halfDoor, y: 0 },
      end: { x: halfDoor, y: 0 },
      layerName: 'Doors',
      color: '#EA580C',
      lineType: 'dashed',
      lineWeight: 0.35,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kapiGenisligi',
    };
    entities.push(doorLine);

    // Handrails (lines along side walls, 50mm from wall, 900mm height position)
    const handrailOffset = 50;
    const handrailStart = d * 0.2;
    const handrailEnd = d * 0.8;

    // Left handrail
    const leftHandrail: LineEntity = {
      id: v4(),
      type: 'line',
      start: { x: -halfW + handrailOffset, y: handrailStart },
      end: { x: -halfW + handrailOffset, y: handrailEnd },
      layerName: 'Cabin',
      color: '#2563EB',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kabinDerinligi',
    };
    entities.push(leftHandrail);

    // Right handrail
    const rightHandrail: LineEntity = {
      id: v4(),
      type: 'line',
      start: { x: halfW - handrailOffset, y: handrailStart },
      end: { x: halfW - handrailOffset, y: handrailEnd },
      layerName: 'Cabin',
      color: '#2563EB',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kabinDerinligi',
    };
    entities.push(rightHandrail);

    // Button panel (small rectangle on right wall)
    const panelW = 60;
    const panelH = 120;
    const panelX = halfW - handrailOffset - panelW;
    const panelY = d * 0.4;
    const buttonPanel: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: panelX, y: panelY },
        { x: panelX + panelW, y: panelY },
        { x: panelX + panelW, y: panelY + panelH },
        { x: panelX, y: panelY + panelH },
      ],
      closed: true,
      layerName: 'Cabin',
      color: '#2563EB',
      lineType: 'continuous',
      lineWeight: 0.18,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kabinGenisligi',
    };
    entities.push(buttonPanel);

    return entities;
  }
}
