import { v4 } from 'uuid';
import type { CadEntity, PolylineEntity, TextEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Control panel parametric block: rectangular cabinet + text label.
 */
export class ControlPanelBlock extends BaseParametricBlock {
  readonly name = 'ControlPanel';
  readonly displayName = 'Control Panel';
  readonly parameterBindings: Record<string, string> = {};
  readonly attributeDefinitions: BlockAttributeDef[] = [
    { tag: 'LABEL', prompt: 'Panel label', defaultValue: 'CTRL', position: { x: 0, y: 0 }, textHeight: 3, visible: true },
  ];

  generate(_params: Record<string, number>): CadEntity[] {
    const entities: CadEntity[] = [];

    const w = 400;
    const h = 600;
    const halfW = w / 2;

    // Cabinet rectangle
    const cabinet: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -halfW, y: 0 },
        { x: halfW, y: 0 },
        { x: halfW, y: h },
        { x: -halfW, y: h },
      ],
      closed: true,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.35,
      visible: true,
      locked: false,
      autoGenerated: true,
    };
    entities.push(cabinet);

    // Label text
    const label: TextEntity = {
      id: v4(),
      type: 'text',
      position: { x: 0, y: h / 2 },
      content: 'CTRL',
      fontSize: 20,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fontStyle: 'normal',
      alignment: 'center',
      rotation: 0,
      layerName: 'Text',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.18,
      visible: true,
      locked: false,
      autoGenerated: true,
    };
    entities.push(label);

    return entities;
  }
}
