import { v4 } from 'uuid';
import type { CadEntity, PolylineEntity, LineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Counterweight parametric block: rectangular frame with filler weights.
 * Bound to beyanYuk (load capacity).
 */
export class CounterweightBlock extends BaseParametricBlock {
  readonly name = 'Counterweight';
  readonly displayName = 'Counterweight';
  readonly parameterBindings: Record<string, string> = {
    load: 'beyanYuk',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [
    { tag: 'LOAD', prompt: 'Load capacity (kg)', defaultValue: '630', position: { x: 0, y: -10 }, textHeight: 2, visible: true },
  ];

  generate(params: Record<string, number>): CadEntity[] {
    const load = params.load ?? 630;
    const entities: CadEntity[] = [];

    // Frame size proportional to load
    const frameW = 200;
    const frameD = 80 + load * 0.05;
    const halfW = frameW / 2;

    // Outer frame
    const frame: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -halfW, y: 0 },
        { x: halfW, y: 0 },
        { x: halfW, y: frameD },
        { x: -halfW, y: frameD },
      ],
      closed: true,
      layerName: 'Counterweight',
      color: '#4B5563',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(frame);

    // Filler weight lines (horizontal lines inside frame)
    const numFillers = Math.min(Math.floor(load / 100), 8);
    const spacing = frameD / (numFillers + 1);
    for (let i = 1; i <= numFillers; i++) {
      const y = spacing * i;
      const filler: LineEntity = {
        id: v4(),
        type: 'line',
        start: { x: -halfW + 5, y },
        end: { x: halfW - 5, y },
        layerName: 'Counterweight',
        color: '#4B5563',
        lineType: 'continuous',
        lineWeight: 0.18,
        visible: true,
        locked: false,
        autoGenerated: true,
        sourceParam: 'beyanYuk',
      };
      entities.push(filler);
    }

    return entities;
  }
}
