import { v4 } from 'uuid';
import type { CadEntity, PolylineEntity, LineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Door parametric block: telescopic or center-opening panels.
 * Bound to kapiGenisligi.
 */
export class DoorBlock extends BaseParametricBlock {
  readonly name = 'Door';
  readonly displayName = 'Door';
  readonly parameterBindings: Record<string, string> = {
    doorWidth: 'kapiGenisligi',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [
    { tag: 'TYPE', prompt: 'Door type', defaultValue: 'telescopic', position: { x: 0, y: -10 }, textHeight: 2, visible: true },
  ];

  generate(params: Record<string, number>): CadEntity[] {
    const doorW = params.doorWidth ?? 800;
    const entities: CadEntity[] = [];
    const panelThickness = 30;
    const halfDoor = doorW / 2;

    // Two sliding panels (center-opening style)
    // Left panel
    const leftPanel: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -halfDoor, y: 0 },
        { x: 0, y: 0 },
        { x: 0, y: panelThickness },
        { x: -halfDoor, y: panelThickness },
      ],
      closed: true,
      layerName: 'Doors',
      color: '#EA580C',
      lineType: 'continuous',
      lineWeight: 0.35,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kapiGenisligi',
    };
    entities.push(leftPanel);

    // Right panel
    const rightPanel: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: 0, y: 0 },
        { x: halfDoor, y: 0 },
        { x: halfDoor, y: panelThickness },
        { x: 0, y: panelThickness },
      ],
      closed: true,
      layerName: 'Doors',
      color: '#EA580C',
      lineType: 'continuous',
      lineWeight: 0.35,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kapiGenisligi',
    };
    entities.push(rightPanel);

    // Door track line
    const track: LineEntity = {
      id: v4(),
      type: 'line',
      start: { x: -halfDoor - 50, y: -10 },
      end: { x: halfDoor + 50, y: -10 },
      layerName: 'Doors',
      color: '#EA580C',
      lineType: 'center',
      lineWeight: 0.18,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kapiGenisligi',
    };
    entities.push(track);

    return entities;
  }
}
