import { v4 } from 'uuid';
import type { CadEntity, CircleEntity, LineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Governor parametric block: sheave circle + rope lines.
 */
export class GovernorBlock extends BaseParametricBlock {
  readonly name = 'Governor';
  readonly displayName = 'Governor';
  readonly parameterBindings: Record<string, string> = {
    load: 'beyanYuk',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [];

  generate(params: Record<string, number>): CadEntity[] {
    const load = params.load ?? 630;
    const entities: CadEntity[] = [];

    const sheaveRadius = 100 + load * 0.02;

    // Sheave circle
    const sheave: CircleEntity = {
      id: v4(),
      type: 'circle',
      center: { x: 0, y: 0 },
      radius: sheaveRadius,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(sheave);

    // Rope lines (vertical, extending from sheave)
    const ropeLeft: LineEntity = {
      id: v4(),
      type: 'line',
      start: { x: -sheaveRadius * 0.3, y: -sheaveRadius },
      end: { x: -sheaveRadius * 0.3, y: -sheaveRadius * 3 },
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.18,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(ropeLeft);

    const ropeRight: LineEntity = {
      id: v4(),
      type: 'line',
      start: { x: sheaveRadius * 0.3, y: -sheaveRadius },
      end: { x: sheaveRadius * 0.3, y: -sheaveRadius * 3 },
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.18,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(ropeRight);

    return entities;
  }
}
