import { v4 } from 'uuid';
import type { CadEntity, PolylineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Guide rail parametric block: T-profile cross-section polyline.
 * Bound to rail spec width and height.
 */
export class GuideRailBlock extends BaseParametricBlock {
  readonly name = 'GuideRail';
  readonly displayName = 'Guide Rail (T-Profile)';
  readonly parameterBindings: Record<string, string> = {
    width: 'cabinRailSpec.width',
    height: 'cabinRailSpec.height',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [
    { tag: 'MODEL', prompt: 'Rail model', defaultValue: 'T89/B', position: { x: 0, y: -10 }, textHeight: 2, visible: true },
  ];

  generate(params: Record<string, number>): CadEntity[] {
    const w = params.width ?? 89;
    const h = params.height ?? 62;
    const entities: CadEntity[] = [];

    // T-profile cross section — centered at origin
    const flangeW = w;
    const flangeH = h * 0.25;
    const webW = w * 0.2;
    const webH = h - flangeH;
    const halfFlange = flangeW / 2;
    const halfWeb = webW / 2;

    const profile: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -halfFlange, y: 0 },
        { x: halfFlange, y: 0 },
        { x: halfFlange, y: flangeH },
        { x: halfWeb, y: flangeH },
        { x: halfWeb, y: flangeH + webH },
        { x: -halfWeb, y: flangeH + webH },
        { x: -halfWeb, y: flangeH },
        { x: -halfFlange, y: flangeH },
      ],
      closed: true,
      layerName: 'Rails',
      color: '#DC2626',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'kabinRayStr',
    };
    entities.push(profile);

    return entities;
  }
}
