import { v4 } from 'uuid';
import type { CadEntity, PolylineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Safety gear parametric block: wedge profile polyline.
 */
export class SafetyGearBlock extends BaseParametricBlock {
  readonly name = 'SafetyGear';
  readonly displayName = 'Safety Gear';
  readonly parameterBindings: Record<string, string> = {
    load: 'beyanYuk',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [];

  generate(params: Record<string, number>): CadEntity[] {
    const load = params.load ?? 630;
    const entities: CadEntity[] = [];

    const w = 80 + load * 0.02;
    const h = 60 + load * 0.015;
    const halfW = w / 2;

    // Wedge profile
    const wedge: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -halfW, y: 0 },
        { x: halfW, y: 0 },
        { x: halfW * 0.6, y: h },
        { x: -halfW * 0.6, y: h },
      ],
      closed: true,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(wedge);

    return entities;
  }
}
