import { v4 } from 'uuid';
import type { CadEntity, CircleEntity, PolylineEntity, BlockAttributeDef } from '../core/types';
import { BaseParametricBlock } from './BlockDefinition';

/**
 * Traction machine parametric block: motor circle + sheave circle + base rectangle.
 */
export class TractionMachineBlock extends BaseParametricBlock {
  readonly name = 'TractionMachine';
  readonly displayName = 'Traction Machine';
  readonly parameterBindings: Record<string, string> = {
    load: 'beyanYuk',
  };
  readonly attributeDefinitions: BlockAttributeDef[] = [
    { tag: 'TYPE', prompt: 'Machine type', defaultValue: 'Gearless', position: { x: 0, y: -15 }, textHeight: 2, visible: true },
  ];

  generate(params: Record<string, number>): CadEntity[] {
    const load = params.load ?? 630;
    const entities: CadEntity[] = [];

    // Scale based on load
    const motorRadius = 150 + load * 0.05;
    const sheaveRadius = 200 + load * 0.03;

    // Base rectangle
    const baseW = motorRadius * 3;
    const baseH = motorRadius * 2;
    const base: PolylineEntity = {
      id: v4(),
      type: 'polyline',
      vertices: [
        { x: -baseW / 2, y: -baseH / 2 },
        { x: baseW / 2, y: -baseH / 2 },
        { x: baseW / 2, y: baseH / 2 },
        { x: -baseW / 2, y: baseH / 2 },
      ],
      closed: true,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.35,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(base);

    // Motor circle
    const motor: CircleEntity = {
      id: v4(),
      type: 'circle',
      center: { x: -motorRadius * 0.5, y: 0 },
      radius: motorRadius,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(motor);

    // Sheave circle
    const sheave: CircleEntity = {
      id: v4(),
      type: 'circle',
      center: { x: motorRadius * 0.8, y: 0 },
      radius: sheaveRadius,
      layerName: '0',
      color: '#FFFFFF',
      lineType: 'continuous',
      lineWeight: 0.25,
      visible: true,
      locked: false,
      autoGenerated: true,
      sourceParam: 'beyanYuk',
    };
    entities.push(sheave);

    return entities;
  }
}
